import type { MetricDefinition } from '@org/types';

export const METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  totalUsers: {
    id: 'totalUsers',
    name: 'Total Users',
    description: 'Total registered user accounts across the platform regardless of status.',
    source: 'PostgreSQL `User` table count',
    calculation: 'COUNT(*) from User',
    freshness: 'Real-time',
    category: 'Platform',
    unit: 'accounts',
  },
  activeUsers: {
    id: 'activeUsers',
    name: 'Active Users (MAU)',
    description: 'Distinct user accounts that established a session or performed an activity within the last 30 days.',
    source: '`RefreshToken` and `RecentActivity` tables',
    calculation: 'COUNT(DISTINCT userId) where active within range',
    freshness: 'Near real-time (15s)',
    category: 'Platform',
    unit: 'users',
  },
  dau: {
    id: 'dau',
    name: 'Daily Active Users (DAU)',
    description: 'Unique accounts active within the past 24 hours.',
    source: '`RefreshToken` activity timestamps',
    calculation: 'COUNT(DISTINCT userId) where activity >= now() - 24h',
    freshness: 'Real-time',
    category: 'User Engagement',
    unit: 'users',
  },
  wau: {
    id: 'wau',
    name: 'Weekly Active Users (WAU)',
    description: 'Unique accounts active within the past 7 days.',
    source: '`RefreshToken` activity timestamps',
    calculation: 'COUNT(DISTINCT userId) where activity >= now() - 7d',
    freshness: 'Near real-time',
    category: 'User Engagement',
    unit: 'users',
  },
  mau: {
    id: 'mau',
    name: 'Monthly Active Users (MAU)',
    description: 'Unique accounts active within the past 30 days.',
    source: '`RefreshToken` activity timestamps',
    calculation: 'COUNT(DISTINCT userId) where activity >= now() - 30d',
    freshness: 'Near real-time',
    category: 'User Engagement',
    unit: 'users',
  },
  dauMauRatio: {
    id: 'dauMauRatio',
    name: 'DAU / MAU Stickiness Ratio',
    description: 'Percentage of monthly active users who engage on any given day, measuring platform retention & stickiness.',
    source: 'DAU / MAU * 100',
    calculation: '(DAU / MAU) * 100',
    freshness: 'Near real-time',
    category: 'User Engagement',
    unit: '%',
  },
  totalWorkspaces: {
    id: 'totalWorkspaces',
    name: 'Total Workspaces',
    description: 'Number of collaborative tenant workspaces provisioned.',
    source: '`Workspace` table count',
    calculation: 'COUNT(*) from Workspace',
    freshness: 'Real-time',
    category: 'Platform',
    unit: 'workspaces',
  },
  mrr: {
    id: 'mrr',
    name: 'Monthly Recurring Revenue (MRR)',
    description: 'Normalized monthly subscription revenue across all paid active workspaces.',
    source: '`WorkspaceSubscription` combined with `PLANS_CONFIG` tier pricing and seat allocations',
    calculation: 'SUM(seats * tierMonthlyPrice) for all ACTIVE subscriptions',
    freshness: 'Near real-time',
    category: 'Revenue',
    unit: 'USD',
  },
  arr: {
    id: 'arr',
    name: 'Annual Recurring Revenue (ARR)',
    description: 'Annualized recurring revenue based on current MRR.',
    source: 'MRR * 12',
    calculation: 'MRR * 12',
    freshness: 'Near real-time',
    category: 'Revenue',
    unit: 'USD',
  },
  storageConsumed: {
    id: 'storageConsumed',
    name: 'Storage Consumed',
    description: 'Total disk and object storage utilized by all uploaded files across all workspaces.',
    source: '`Upload` table aggregated size',
    calculation: 'SUM(size) from Upload',
    freshness: 'Real-time',
    category: 'Files',
    unit: 'bytes',
  },
  apiRequests: {
    id: 'apiRequests',
    name: 'API Requests',
    description: 'Total HTTP and external integration API calls processed within the time window.',
    source: '`IntegrationAuditLog` and telemetry metrics',
    calculation: 'COUNT(*) from IntegrationAuditLog',
    freshness: 'Real-time',
    category: 'APIs',
    unit: 'requests',
  },
  apiErrorRate: {
    id: 'apiErrorRate',
    name: 'API Error Rate',
    description: 'Percentage of processed API requests that resulted in non-2xx status codes.',
    source: 'Failed requests / Total requests * 100',
    calculation: '(Failed / Total) * 100',
    freshness: 'Real-time',
    category: 'APIs',
    unit: '%',
  },
  webVsDesktop: {
    id: 'webVsDesktop',
    name: 'Platform Usage Split',
    description: 'Breakdown of active sessions originated from Web Browser vs Native Desktop (Electron) app.',
    source: 'User-Agent header parsed via `@org/platform` `detectDeviceEnvironment`',
    calculation: 'GROUP BY environment (electron vs browser)',
    freshness: 'Real-time',
    category: 'Platform Usage',
    unit: 'sessions',
  },
};
