// Complete App Connector Catalog for AI Agent Studio
// Supporting 35+ production connectors across Communication, Email, Calendar,
// Project Management, CRM, Development, Productivity, Database, AI, Web/Automation, Storage.

export const CONNECTOR_CATEGORIES = [
  { id: 'all', label: 'All Categories', icon: 'Layers' },
  { id: 'communication', label: 'Communication', icon: 'MessageSquare', description: 'Chat, messaging, channels & bots' },
  { id: 'email', label: 'Email', icon: 'Mail', description: 'Mail delivery, threads & inbox management' },
  { id: 'calendar', label: 'Calendar', icon: 'Calendar', description: 'Schedules, meetings & calendar events' },
  { id: 'project_management', label: 'Project Management', icon: 'CheckSquare', description: 'Tasks, sprints, issues & tracking' },
  { id: 'crm', label: 'CRM', icon: 'Users', description: 'Leads, customer pipelines & contacts' },
  { id: 'development', label: 'Development', icon: 'GitBranch', description: 'Repositories, pull requests & CI/CD' },
  { id: 'productivity', label: 'Productivity', icon: 'FileText', description: 'Documents, wikis, notes & spreadsheets' },
  { id: 'storage', label: 'Storage', icon: 'HardDrive', description: 'Object storage, buckets & asset files' },
  { id: 'database', label: 'Databases', icon: 'Database', description: 'SQL, NoSQL, caches & change streams' },
  { id: 'analytics', label: 'Analytics', icon: 'BarChart', description: 'Metrics, tracking & business intelligence' },
  { id: 'payments', label: 'Payments & Finance', icon: 'CreditCard', description: 'Invoices, subscriptions, transactions' },
  { id: 'customer_support', label: 'Customer Support', icon: 'Headphones', description: 'Tickets, helpdesk & customer queries' },
  { id: 'ai', label: 'AI & LLM', icon: 'Bot', description: 'LLMs, multimodal models & inference providers' },
  { id: 'web_automation', label: 'Web / Automation', icon: 'Globe', description: 'REST APIs, webhooks, Firecrawl & MCP' },
  { id: 'security', label: 'Security & Auth', icon: 'Shield', description: 'Identity, secrets & audit compliance' },
  { id: 'custom', label: 'Custom & Internal', icon: 'Code', description: 'User-defined APIs, OpenAPI & internal services' },
];

export const CONNECTOR_CATALOG = [
  // ==========================================
  // 1. COMMUNICATION
  // ==========================================
  {
    id: 'microsoft_teams',
    name: 'Microsoft Teams',
    category: 'communication',
    icon: 'MessageSquare',
    color: '#5b5fc7',
    authType: 'OAUTH2',
    description: 'Connect enterprise Microsoft Teams to send channel messages, chat in direct messages, search conversations, and book online meetings.',
    verified: true,
    version: 'v2.4.0',
    status: 'connected',
    providerKey: 'MICROSOFT_TEAMS',
    docsUrl: 'https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview',
    defaultAccount: 'Engineering Teams Lead (engineering@company.com)',
    connectionsCount: 2,
    actions: [
      {
        id: 'list_teams',
        name: 'List Teams',
        description: 'Retrieves all Microsoft Teams joined or accessible by the user.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { properties: { maxResults: { type: 'number', default: 50 } } },
        outputSchema: { properties: { teams: { type: 'array' } } },
      },
      {
        id: 'get_team',
        name: 'Get Team',
        description: 'Fetches metadata, settings, and description for a specific Team.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { required: ['teamId'], properties: { teamId: { type: 'string', label: 'Team ID' } } },
        outputSchema: { properties: { team: { type: 'object' } } },
      },
      {
        id: 'list_channels',
        name: 'List Channels',
        description: 'Lists all channels (standard and private) inside a Team.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { required: ['teamId'], properties: { teamId: { type: 'string', label: 'Team ID' } } },
        outputSchema: { properties: { channels: { type: 'array' } } },
      },
      {
        id: 'get_channel',
        name: 'Get Channel',
        description: 'Gets details, topic, and membership type of a channel.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { required: ['teamId', 'channelId'], properties: { teamId: { type: 'string', label: 'Team ID' }, channelId: { type: 'string', label: 'Channel ID' } } },
        outputSchema: { properties: { channel: { type: 'object' } } },
      },
      {
        id: 'get_members',
        name: 'Get Members',
        description: 'Retrieves member list and roles for a specific Team or Channel.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { required: ['teamId'], properties: { teamId: { type: 'string', label: 'Team ID' }, channelId: { type: 'string', label: 'Channel ID (optional)' } } },
        outputSchema: { properties: { members: { type: 'array' } } },
      },
      {
        id: 'send_channel_message',
        name: 'Send Channel Message',
        description: 'Posts a formatted message or Adaptive Card to a Microsoft Teams channel.',
        permissionLevel: 'write',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['teamId', 'channelId', 'content'],
          properties: {
            teamId: { type: 'string', label: 'Team', default: 'Engineering' },
            channelId: { type: 'string', label: 'Channel', default: 'General' },
            content: { type: 'string', label: 'Message Text / Dynamic Expression', default: '{{agent.summary}}' },
            subject: { type: 'string', label: 'Subject Heading (Optional)' },
            contentType: { type: 'string', enum: ['text', 'html', 'markdown'], default: 'text' },
          },
        },
        outputSchema: { properties: { messageId: { type: 'string' }, webUrl: { type: 'string' }, createdDateTime: { type: 'string' } } },
      },
      {
        id: 'send_direct_message',
        name: 'Send Direct Message',
        description: 'Sends a direct 1-on-1 chat or group notification to a user in Teams.',
        permissionLevel: 'write',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['userId', 'content'],
          properties: {
            userId: { type: 'string', label: 'User Email / Object ID' },
            content: { type: 'string', label: 'Message Text' },
          },
        },
        outputSchema: { properties: { chatId: { type: 'string' }, messageId: { type: 'string' } } },
      },
      {
        id: 'search_messages',
        name: 'Search Messages',
        description: 'Searches messages across channels and chats matching keyword query.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['query'],
          properties: {
            query: { type: 'string', label: 'Search Query' },
            maxResults: { type: 'number', default: 25 },
          },
        },
        outputSchema: { properties: { count: { type: 'number' }, messages: { type: 'array' } } },
      },
      {
        id: 'get_message',
        name: 'Get Message',
        description: 'Retrieves a single message by ID from a channel or chat.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['teamId', 'channelId', 'messageId'],
          properties: {
            teamId: { type: 'string', label: 'Team ID' },
            channelId: { type: 'string', label: 'Channel ID' },
            messageId: { type: 'string', label: 'Message ID' },
          },
        },
        outputSchema: { properties: { message: { type: 'object' } } },
      },
      {
        id: 'reply_to_message',
        name: 'Reply to Message',
        description: 'Replies in the thread of an existing channel message.',
        permissionLevel: 'write',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['teamId', 'channelId', 'messageId', 'content'],
          properties: {
            teamId: { type: 'string', label: 'Team ID' },
            channelId: { type: 'string', label: 'Channel ID' },
            messageId: { type: 'string', label: 'Parent Message ID' },
            content: { type: 'string', label: 'Reply Text' },
          },
        },
        outputSchema: { properties: { replyId: { type: 'string' }, parentMessageId: { type: 'string' } } },
      },
      {
        id: 'create_meeting',
        name: 'Create Meeting',
        description: 'Schedules a Microsoft Teams online meeting with audio/video join URL.',
        permissionLevel: 'write',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['subject', 'startDateTime', 'endDateTime'],
          properties: {
            subject: { type: 'string', label: 'Meeting Subject', default: 'AI Agent Sync' },
            startDateTime: { type: 'string', label: 'Start Time (ISO 8601)' },
            endDateTime: { type: 'string', label: 'End Time (ISO 8601)' },
            participants: { type: 'array', label: 'Attendees' },
          },
        },
        outputSchema: { properties: { meetingId: { type: 'string' }, joinWebUrl: { type: 'string' }, subject: { type: 'string' } } },
      },
      {
        id: 'get_meeting',
        name: 'Get Meeting',
        description: 'Retrieves details, join link, and attendee status for an online meeting.',
        permissionLevel: 'read',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: { required: ['meetingId'], properties: { meetingId: { type: 'string', label: 'Meeting ID' } } },
        outputSchema: { properties: { meeting: { type: 'object' } } },
      },
      {
        id: 'update_meeting',
        name: 'Update Meeting',
        description: 'Updates time, subject, or participants for a scheduled meeting.',
        permissionLevel: 'write',
        requiresConfirmation: false,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['meetingId'],
          properties: {
            meetingId: { type: 'string', label: 'Meeting ID' },
            subject: { type: 'string', label: 'New Subject' },
            startDateTime: { type: 'string', label: 'New Start Time' },
            endDateTime: { type: 'string', label: 'New End Time' },
          },
        },
        outputSchema: { properties: { meetingId: { type: 'string' }, status: { type: 'string' } } },
      },
      {
        id: 'cancel_meeting',
        name: 'Cancel Meeting',
        description: 'Cancels an existing Microsoft Teams online meeting and alerts attendees.',
        permissionLevel: 'destructive',
        requiresConfirmation: true,
        supportsDynamicInputs: true,
        inputSchema: {
          required: ['meetingId'],
          properties: {
            meetingId: { type: 'string', label: 'Meeting ID' },
            comment: { type: 'string', label: 'Cancellation Reason' },
          },
        },
        outputSchema: { properties: { meetingId: { type: 'string' }, cancelled: { type: 'boolean' } } },
      },
    ],
    triggers: [
      {
        id: 'new_message',
        name: 'New Message in Channel',
        description: 'Fires whenever a new message is posted to a monitored Teams channel.',
        eventType: 'microsoft.teams.channel.message.created',
        payloadSchema: {
          properties: {
            teamId: { type: 'string' },
            channelId: { type: 'string' },
            messageId: { type: 'string' },
            body: { type: 'string' },
            fromUser: { type: 'string' },
          },
        },
      },
      {
        id: 'mention',
        name: 'Bot or User Mentioned',
        description: 'Fires when the AI Agent or a monitored user is @mentioned in Teams.',
        eventType: 'microsoft.teams.channel.mention',
        payloadSchema: {
          properties: {
            teamId: { type: 'string' },
            channelId: { type: 'string' },
            messageId: { type: 'string' },
            mentionedUser: { type: 'string' },
            content: { type: 'string' },
          },
        },
      },
      {
        id: 'meeting_event',
        name: 'Meeting Created or Changed',
        description: 'Fires when an online meeting is booked, updated, or started.',
        eventType: 'microsoft.teams.meeting.created',
        payloadSchema: {
          properties: {
            meetingId: { type: 'string' },
            subject: { type: 'string' },
            joinWebUrl: { type: 'string' },
            startDateTime: { type: 'string' },
          },
        },
      },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    icon: 'MessageSquare',
    color: '#4a154b',
    authType: 'OAUTH2',
    description: 'Post channel notifications, handle button interactions, listen for thread replies, and monitor channel mentions.',
    verified: true,
    version: 'v2.1.0',
    status: 'connected',
    providerKey: 'SLACK',
    docsUrl: 'https://api.slack.com',
    defaultAccount: 'OneTab Workspace Bot (#general)',
    connectionsCount: 1,
    actions: [
      { id: 'send_message', name: 'Send Channel Message', description: 'Posts message to Slack channel', permissionLevel: 'write', requiresConfirmation: false, inputSchema: { required: ['channelId', 'text'], properties: { channelId: { type: 'string' }, text: { type: 'string' } } } },
      { id: 'reply_in_thread', name: 'Reply in Thread', description: 'Replies to a specific Slack thread', permissionLevel: 'write', requiresConfirmation: false, inputSchema: { required: ['channelId', 'threadTs', 'text'], properties: { channelId: { type: 'string' }, threadTs: { type: 'string' }, text: { type: 'string' } } } },
      { id: 'search_messages', name: 'Search Messages', description: 'Searches message history in Slack', permissionLevel: 'read', requiresConfirmation: false, inputSchema: { required: ['query'], properties: { query: { type: 'string' } } } },
      { id: 'list_channels', name: 'List Channels', description: 'Lists public and private channels', permissionLevel: 'read', requiresConfirmation: false, inputSchema: { properties: {} } },
      { id: 'get_channel', name: 'Get Channel Info', description: 'Retrieves metadata for channel', permissionLevel: 'read', requiresConfirmation: false, inputSchema: { required: ['channelId'], properties: { channelId: { type: 'string' } } } },
      { id: 'add_reaction', name: 'Add Reaction', description: 'Adds emoji reaction to message', permissionLevel: 'write', requiresConfirmation: false, inputSchema: { required: ['channelId', 'timestamp', 'emoji'], properties: { channelId: { type: 'string' }, timestamp: { type: 'string' }, emoji: { type: 'string' } } } },
    ],
    triggers: [
      { id: 'new_message', name: 'New Message in Channel', description: 'Triggers on new message in channel', eventType: 'slack.message' },
      { id: 'mention', name: 'App Mentioned', description: 'Triggers when @agent is mentioned', eventType: 'slack.app_mention' },
      { id: 'reaction_added', name: 'Reaction Added', description: 'Triggers on new reaction', eventType: 'slack.reaction_added' },
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'communication',
    icon: 'Radio',
    color: '#5865f2',
    authType: 'API_KEY',
    description: 'Send alerts to Discord servers and channels, manage role mentions, and listen to guild events.',
    verified: true,
    version: 'v1.0.0',
    status: 'disconnected',
    providerKey: 'DISCORD',
    actions: [
      { id: 'send_channel_message', name: 'Send Channel Message', description: 'Post embed or text message to Discord channel' },
      { id: 'send_direct_message', name: 'Send Direct Message', description: 'DM a server member' },
      { id: 'create_thread', name: 'Create Thread', description: 'Create public or private channel thread' },
    ],
    triggers: [
      { id: 'message_created', name: 'New Message', description: 'Fires when a message is posted' },
      { id: 'member_joined', name: 'Member Joined', description: 'Fires when member joins guild' },
    ],
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'communication',
    icon: 'Send',
    color: '#229ed9',
    authType: 'API_KEY',
    description: 'Deliver instant notifications, inline keyboards, media alerts, and agent responses to Telegram chats.',
    verified: true,
    version: 'v1.2.0',
    status: 'disconnected',
    providerKey: 'TELEGRAM',
    actions: [
      { id: 'send_message', name: 'Send Message', description: 'Sends message to chat or channel' },
      { id: 'send_photo', name: 'Send Photo / Document', description: 'Sends image or document payload' },
      { id: 'send_poll', name: 'Send Interactive Poll', description: 'Create multi-choice poll' },
    ],
    triggers: [
      { id: 'new_chat_message', name: 'New Chat Message', description: 'Fires on inbound Telegram message' },
    ],
  },

  // ==========================================
  // 2. EMAIL
  // ==========================================
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'email',
    icon: 'Mail',
    color: '#ea4335',
    authType: 'OAUTH2',
    description: 'Search customer emails, read threads, draft intelligent replies, and send automated transactional messages.',
    verified: true,
    version: 'v2.2.0',
    status: 'connected',
    providerKey: 'GMAIL',
    defaultAccount: 'support-ops@company.com',
    connectionsCount: 1,
    actions: [
      { id: 'send_email', name: 'Send Email', description: 'Dispatches email to recipient', permissionLevel: 'write', requiresConfirmation: false },
      { id: 'reply_to_email', name: 'Reply to Thread', description: 'Replies in existing email thread', permissionLevel: 'write', requiresConfirmation: false },
      { id: 'create_draft', name: 'Create Draft', description: 'Creates draft for human review', permissionLevel: 'write', requiresConfirmation: false },
      { id: 'search_emails', name: 'Search Emails', description: 'Finds emails matching query', permissionLevel: 'read', requiresConfirmation: false },
      { id: 'get_thread', name: 'Get Thread', description: 'Fetches entire email conversation', permissionLevel: 'read', requiresConfirmation: false },
    ],
    triggers: [
      { id: 'new_email', name: 'New Email Received', description: 'Triggers on incoming email matching filters', eventType: 'gmail.message.received' },
      { id: 'new_attachment', name: 'Attachment Received', description: 'Triggers on incoming PDF/doc attachment', eventType: 'gmail.attachment.received' },
    ],
  },
  {
    id: 'outlook',
    name: 'Microsoft Outlook',
    category: 'email',
    icon: 'Mail',
    color: '#0078d4',
    authType: 'OAUTH2',
    description: 'Access Microsoft 365 Outlook mailboxes to send emails, manage draft messages, and search inbox archives.',
    verified: true,
    version: 'v1.8.0',
    status: 'disconnected',
    providerKey: 'OUTLOOK',
    actions: [
      { id: 'send_mail', name: 'Send Mail', description: 'Sends email via Microsoft Graph' },
      { id: 'create_draft', name: 'Create Draft Mail', description: 'Creates Outlook draft' },
      { id: 'search_mail', name: 'Search Mailbox', description: 'Search emails by sender or keyword' },
    ],
    triggers: [
      { id: 'mail_received', name: 'Mail Received', description: 'Triggers when new email arrives' },
    ],
  },

  // ==========================================
  // 3. CALENDAR
  // ==========================================
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    category: 'calendar',
    icon: 'Calendar',
    color: '#4285f4',
    authType: 'OAUTH2',
    description: 'Check attendee availability, schedule meetings, update calendar entries, and book Google Meet conferences.',
    verified: true,
    version: 'v2.0.0',
    status: 'connected',
    providerKey: 'GOOGLE_CALENDAR',
    defaultAccount: 'primary-calendar@company.com',
    connectionsCount: 1,
    actions: [
      { id: 'create_event', name: 'Create Event / Meeting', description: 'Books event with Google Meet link' },
      { id: 'get_event', name: 'Get Event Details', description: 'Fetches calendar event data' },
      { id: 'update_event', name: 'Update Event', description: 'Reschedules or edits participants' },
      { id: 'list_events', name: 'List Upcoming Events', description: 'Retrieves agenda for timeframe' },
      { id: 'check_availability', name: 'Check Free / Busy', description: 'Queries free/busy schedule slots' },
    ],
    triggers: [
      { id: 'event_created', name: 'Event Created', description: 'Fires when new event is scheduled' },
      { id: 'event_starts_soon', name: 'Event Starting Soon', description: 'Fires 10m before meeting begins' },
    ],
  },
  {
    id: 'outlook_calendar',
    name: 'Outlook Calendar',
    category: 'calendar',
    icon: 'Calendar',
    color: '#0078d4',
    authType: 'OAUTH2',
    description: 'Schedule corporate appointments, check calendar availability, and book Microsoft Teams meetings.',
    verified: true,
    version: 'v1.4.0',
    status: 'disconnected',
    providerKey: 'OUTLOOK_CALENDAR',
    actions: [
      { id: 'create_event', name: 'Create Calendar Event', description: 'Schedules event in Microsoft 365' },
      { id: 'list_events', name: 'List Events', description: 'Fetches calendar agenda' },
    ],
    triggers: [
      { id: 'event_alert', name: 'Event Reminder', description: 'Fires on upcoming calendar event' },
    ],
  },

  // ==========================================
  // 4. PROJECT MANAGEMENT
  // ==========================================
  {
    id: 'jira',
    name: 'Jira Software',
    category: 'project_management',
    icon: 'CheckSquare',
    color: '#0052cc',
    authType: 'OAUTH2',
    description: 'Create and track software tickets, update sprint boards, transitions issues, and attach AI summaries.',
    verified: true,
    version: 'v2.5.0',
    status: 'disconnected',
    providerKey: 'JIRA',
    actions: [
      { id: 'create_issue', name: 'Create Jira Issue', description: 'Creates bug, task, or story ticket' },
      { id: 'update_issue', name: 'Update Issue Status', description: 'Moves issue through workflow transitions' },
      { id: 'add_comment', name: 'Add Issue Comment', description: 'Appends notes or findings' },
      { id: 'search_issues', name: 'Search JQL Issues', description: 'Queries issues using JQL syntax' },
    ],
    triggers: [
      { id: 'issue_created', name: 'Issue Created', description: 'Fires when new ticket is filed' },
      { id: 'issue_updated', name: 'Issue Status Changed', description: 'Fires on status transition' },
    ],
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'project_management',
    icon: 'CheckSquare',
    color: '#5e6ad2',
    authType: 'OAUTH2',
    description: 'High-speed project management. Create issues, assign cycles, link pull requests, and manage engineering backlogs.',
    verified: true,
    version: 'v2.1.0',
    status: 'connected',
    providerKey: 'LINEAR',
    defaultAccount: 'Engineering Core (linear.app/onetab)',
    connectionsCount: 1,
    actions: [
      { id: 'create_issue', name: 'Create Issue', description: 'Creates new issue in team backlog' },
      { id: 'update_issue', name: 'Update Issue', description: 'Edits title, state, or assignee' },
      { id: 'search_issues', name: 'Search Issues', description: 'Filters issues by status and project' },
      { id: 'add_comment', name: 'Add Comment', description: 'Posts markdown comment to issue' },
    ],
    triggers: [
      { id: 'issue_created', name: 'Issue Created', description: 'Triggers on new Linear issue' },
      { id: 'issue_completed', name: 'Issue Done', description: 'Triggers when issue is marked Completed' },
    ],
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'project_management',
    icon: 'CheckSquare',
    color: '#f06a6a',
    authType: 'OAUTH2',
    description: 'Manage marketing campaigns, cross-functional sprints, task milestones, and team portfolios in Asana.',
    verified: true,
    version: 'v1.6.0',
    status: 'disconnected',
    providerKey: 'ASANA',
    actions: [
      { id: 'create_task', name: 'Create Task', description: 'Creates task in project' },
      { id: 'update_task', name: 'Update Task', description: 'Updates status or due date' },
      { id: 'list_tasks', name: 'List Project Tasks', description: 'Fetches tasks in milestone' },
    ],
    triggers: [
      { id: 'task_added', name: 'Task Added', description: 'Fires when task is added' },
    ],
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'project_management',
    icon: 'CheckSquare',
    color: '#7b68ee',
    authType: 'API_KEY',
    description: 'Create tasks, track custom fields, manage checklists, and update statuses across ClickUp spaces.',
    verified: true,
    version: 'v1.2.0',
    status: 'disconnected',
    providerKey: 'CLICKUP',
    actions: [
      { id: 'create_task', name: 'Create Task', description: 'Creates task in ClickUp list' },
      { id: 'get_task', name: 'Get Task Details', description: 'Fetches custom field values' },
    ],
    triggers: [
      { id: 'task_status_updated', name: 'Status Updated', description: 'Fires on task state change' },
    ],
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'project_management',
    icon: 'Trello',
    color: '#0079bf',
    authType: 'OAUTH2',
    description: 'Move cards on Kanban boards, add checklists, set due dates, and post comments on Trello lists.',
    verified: true,
    version: 'v1.5.0',
    status: 'disconnected',
    providerKey: 'TRELLO',
    actions: [
      { id: 'create_card', name: 'Create Card', description: 'Creates new card on list' },
      { id: 'move_card', name: 'Move Card', description: 'Moves card to destination list' },
    ],
    triggers: [
      { id: 'card_created', name: 'Card Created', description: 'Fires when card is created' },
    ],
  },

  // ==========================================
  // 5. CRM
  // ==========================================
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'crm',
    icon: 'Users',
    color: '#00a1e0',
    authType: 'OAUTH2',
    description: 'Query enterprise leads, update Opportunity stages, create Contact records, and sync account intelligence.',
    verified: true,
    version: 'v2.8.0',
    status: 'disconnected',
    providerKey: 'SALESFORCE',
    actions: [
      { id: 'create_lead', name: 'Create Lead', description: 'Inserts new sales lead into Salesforce' },
      { id: 'update_opportunity', name: 'Update Opportunity', description: 'Changes deal stage and amount' },
      { id: 'query_soql', name: 'Run SOQL Query', description: 'Executes Salesforce SOQL query' },
      { id: 'get_contact', name: 'Get Contact Details', description: 'Retrieves customer record' },
    ],
    triggers: [
      { id: 'lead_created', name: 'Lead Created', description: 'Fires when new lead enters pipeline' },
      { id: 'deal_won', name: 'Opportunity Won', description: 'Fires when deal enters Closed Won' },
    ],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'crm',
    icon: 'Users',
    color: '#ff7a59',
    authType: 'OAUTH2',
    description: 'Automate inbound marketing, sync CRM contacts, log customer engagement calls, and manage deal stages.',
    verified: true,
    version: 'v2.3.0',
    status: 'connected',
    providerKey: 'HUBSPOT',
    defaultAccount: 'HubSpot Marketing Hub (Tier Enterprise)',
    connectionsCount: 1,
    actions: [
      { id: 'create_contact', name: 'Create / Update Contact', description: 'Upserts contact properties' },
      { id: 'create_deal', name: 'Create Deal', description: 'Opens new sales pipeline deal' },
      { id: 'search_contacts', name: 'Search Contacts', description: 'Filters contacts by email or domain' },
    ],
    triggers: [
      { id: 'contact_created', name: 'New Contact Added', description: 'Fires on inbound form lead' },
      { id: 'deal_stage_changed', name: 'Deal Stage Changed', description: 'Fires on stage transition' },
    ],
  },

  // ==========================================
  // 6. DEVELOPMENT
  // ==========================================
  {
    id: 'github',
    name: 'GitHub',
    category: 'development',
    icon: 'GitBranch',
    color: '#24292e',
    authType: 'OAUTH2',
    description: 'Review pull requests, triage issues, trigger GitHub Actions workflows, create commit comments, and inspect repo code.',
    verified: true,
    version: 'v2.9.0',
    status: 'connected',
    providerKey: 'GITHUB',
    defaultAccount: 'onetab-ai-org (Read/Write)',
    connectionsCount: 1,
    actions: [
      { id: 'create_issue', name: 'Create Issue', description: 'Creates bug or feature issue in repo' },
      { id: 'get_pull_request', name: 'Get Pull Request', description: 'Inspects PR diff and comments' },
      { id: 'create_pr_review', name: 'Submit PR Review', description: 'Posts automated code review' },
      { id: 'dispatch_workflow', name: 'Trigger Actions Workflow', description: 'Dispatches repository workflow' },
      { id: 'search_code', name: 'Search Code', description: 'Searches repository files' },
    ],
    triggers: [
      { id: 'pr_opened', name: 'Pull Request Opened', description: 'Triggers on newly submitted PR' },
      { id: 'issue_created', name: 'Issue Created', description: 'Triggers on new issue submission' },
      { id: 'push_commit', name: 'Commit Pushed', description: 'Triggers when commits are pushed' },
    ],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'development',
    icon: 'GitBranch',
    color: '#fc6d26',
    authType: 'OAUTH2',
    description: 'Trigger CI pipelines, review Merge Requests, manage repository branches, and automate issue triage.',
    verified: true,
    version: 'v1.4.0',
    status: 'disconnected',
    providerKey: 'GITLAB',
    actions: [
      { id: 'create_issue', name: 'Create Issue', description: 'Creates issue in project' },
      { id: 'create_mr_comment', name: 'Comment on Merge Request', description: 'Posts review notes' },
    ],
    triggers: [
      { id: 'mr_opened', name: 'Merge Request Opened', description: 'Triggers on new MR' },
    ],
  },

  // ==========================================
  // 7. PRODUCTIVITY
  // ==========================================
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivity',
    icon: 'FileText',
    color: '#000000',
    authType: 'OAUTH2',
    description: 'Query Notion databases, append rich markdown blocks, create documentation pages, and sync knowledge bases.',
    verified: true,
    version: 'v2.0.0',
    status: 'connected',
    providerKey: 'NOTION',
    defaultAccount: 'OneTab Product Wiki',
    connectionsCount: 1,
    actions: [
      { id: 'query_database', name: 'Query Database', description: 'Filters and sorts Notion database rows' },
      { id: 'create_page', name: 'Create Page', description: 'Creates child page with rich markdown' },
      { id: 'append_blocks', name: 'Append Content Blocks', description: 'Appends sections or tables to page' },
      { id: 'get_page', name: 'Get Page Content', description: 'Extracts plain text and properties' },
    ],
    triggers: [
      { id: 'page_created', name: 'Page Added to Database', description: 'Fires when new page is created' },
    ],
  },
  {
    id: 'google_drive',
    name: 'Google Drive',
    category: 'productivity',
    icon: 'HardDrive',
    color: '#34a853',
    authType: 'OAUTH2',
    description: 'Search files across shared drives, upload generated reports, extract text content, and manage folder permissions.',
    verified: true,
    version: 'v1.9.0',
    status: 'disconnected',
    providerKey: 'GOOGLE_DRIVE',
    actions: [
      { id: 'search_files', name: 'Search Files', description: 'Queries drive by filename or type' },
      { id: 'upload_file', name: 'Upload File', description: 'Stores generated file in drive' },
      { id: 'get_file_content', name: 'Download File Content', description: 'Extracts file text for reasoning' },
    ],
    triggers: [
      { id: 'file_created', name: 'File Created / Uploaded', description: 'Fires on newly detected file' },
    ],
  },

  // ==========================================
  // 8. DATABASE
  // ==========================================
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    icon: 'Database',
    color: '#336791',
    authType: 'BASIC',
    description: 'Execute parameterized queries, run safe transaction updates, read schema definitions, and listen to change streams.',
    verified: true,
    version: 'v3.1.0',
    status: 'connected',
    providerKey: 'POSTGRESQL',
    defaultAccount: 'Analytics Read-Only Replica (pg-prod-replica)',
    connectionsCount: 1,
    actions: [
      { id: 'execute_query', name: 'Run SQL Query', description: 'Executes parameterized SQL query', permissionLevel: 'read' },
      { id: 'insert_row', name: 'Insert Row', description: 'Inserts record into table', permissionLevel: 'write' },
      { id: 'update_row', name: 'Update Row', description: 'Updates record by primary key', permissionLevel: 'write' },
    ],
    triggers: [
      { id: 'table_row_inserted', name: 'Row Inserted (CDC)', description: 'Fires on change data capture event' },
    ],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    icon: 'Database',
    color: '#47a248',
    authType: 'BASIC',
    description: 'Query document collections, insert structured JSON records, perform aggregations, and listen to Change Streams.',
    verified: true,
    version: 'v2.0.0',
    status: 'disconnected',
    providerKey: 'MONGODB',
    actions: [
      { id: 'find_documents', name: 'Find Documents', description: 'Queries collection with filter syntax' },
      { id: 'insert_document', name: 'Insert Document', description: 'Inserts JSON record into collection' },
      { id: 'run_aggregation', name: 'Run Aggregation Pipeline', description: 'Executes multi-stage aggregation' },
    ],
    triggers: [
      { id: 'collection_change', name: 'Change Stream Event', description: 'Fires on document insert or update' },
    ],
  },
  {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    icon: 'Database',
    color: '#d82c20',
    authType: 'API_KEY',
    description: 'Fast key-value cache access, pub/sub messaging, rate limit counters, and session context storage.',
    verified: true,
    version: 'v1.5.0',
    status: 'disconnected',
    providerKey: 'REDIS',
    actions: [
      { id: 'get_key', name: 'Get Key', description: 'Fetches cached string or JSON' },
      { id: 'set_key', name: 'Set Key with TTL', description: 'Stores value with expiration' },
      { id: 'publish_channel', name: 'Publish Pub/Sub Message', description: 'Emits event on channel' },
    ],
    triggers: [
      { id: 'channel_message', name: 'Pub/Sub Message Received', description: 'Fires when message is published' },
    ],
  },

  // ==========================================
  // 9. AI & MODELS
  // ==========================================
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'ai',
    icon: 'Bot',
    color: '#10a37f',
    authType: 'API_KEY',
    description: 'Invoke GPT-4o, o1, o3-mini reasoning models, generate vector embeddings, and produce DALL-E image assets.',
    verified: true,
    version: 'v3.0.0',
    status: 'connected',
    providerKey: 'OPENAI',
    defaultAccount: 'OpenAI Tier 5 Enterprise (sk-proj-****)',
    connectionsCount: 1,
    actions: [
      { id: 'chat_completion', name: 'Chat Completion', description: 'Invokes reasoning model with prompt' },
      { id: 'create_embedding', name: 'Create Embeddings', description: 'Generates vector embeddings for text' },
      { id: 'structured_json', name: 'Structured JSON Extraction', description: 'Guarantees output matching schema' },
    ],
    triggers: [],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    category: 'ai',
    icon: 'Bot',
    color: '#d97706',
    authType: 'API_KEY',
    description: 'Reason with Claude 3.5 Sonnet and Haiku, process 200k token context windows, and generate detailed analysis.',
    verified: true,
    version: 'v2.5.0',
    status: 'connected',
    providerKey: 'ANTHROPIC',
    defaultAccount: 'Anthropic Workspaces (sk-ant-****)',
    connectionsCount: 1,
    actions: [
      { id: 'message_completion', name: 'Claude Message', description: 'Calls Claude model with system instructions' },
    ],
    triggers: [],
  },
  {
    id: 'google_gemini',
    name: 'Google Gemini',
    category: 'ai',
    icon: 'Sparkles',
    color: '#1a73e8',
    authType: 'API_KEY',
    description: 'Multimodal reasoning with Gemini 1.5 Pro and Flash, million-token context, audio, and video synthesis.',
    verified: true,
    version: 'v2.0.0',
    status: 'connected',
    providerKey: 'GOOGLE_GEMINI',
    defaultAccount: 'Google Cloud Vertex AI',
    connectionsCount: 1,
    actions: [
      { id: 'generate_content', name: 'Generate Content', description: 'Queries Gemini with text, images, or audio' },
    ],
    triggers: [],
  },

  // ==========================================
  // 10. WEB / AUTOMATION
  // ==========================================
  {
    id: 'http_rest',
    name: 'HTTP REST API',
    category: 'web_automation',
    icon: 'Globe',
    color: '#0284c7',
    authType: 'BASIC',
    description: 'Execute arbitrary HTTP GET, POST, PUT, DELETE requests with custom auth headers, query parameters, and payloads.',
    verified: true,
    version: 'v3.0.0',
    status: 'connected',
    providerKey: 'CUSTOM_API',
    defaultAccount: 'Global REST Client',
    connectionsCount: 1,
    actions: [
      { id: 'execute_request', name: 'Execute HTTP Request', description: 'Invokes external API with full config' },
      { id: 'test_endpoint', name: 'Test Endpoint Connectivity', description: 'Validates status code and latency' },
    ],
    triggers: [
      { id: 'inbound_http', name: 'Inbound Webhook Listener', description: 'Receives external HTTP payloads' },
    ],
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'web_automation',
    icon: 'Flame',
    color: '#f97316',
    authType: 'API_KEY',
    description: 'Turn any live website or web application into clean LLM-ready markdown or structured JSON schemas.',
    verified: true,
    version: 'v1.4.2',
    status: 'connected',
    providerKey: 'FIRECRAWL',
    defaultAccount: 'Firecrawl Enterprise (fc-****)',
    connectionsCount: 1,
    actions: [
      { id: 'search', name: 'Web Search', description: 'Searches live web and extracts clean markdown' },
      { id: 'scrape', name: 'Scrape URL', description: 'Scrapes specific page into markdown' },
      { id: 'extract', name: 'Structured Extract', description: 'Extracts JSON matching defined schema' },
    ],
    triggers: [],
  },
  {
    id: 'mcp_servers',
    name: 'MCP Servers',
    category: 'web_automation',
    icon: 'Plug',
    color: '#8b5cf6',
    authType: 'BEARER',
    description: 'Standardized Model Context Protocol servers providing tools, resources, and live database integrations.',
    verified: true,
    version: 'v2.0.0',
    status: 'connected',
    providerKey: 'MCP',
    defaultAccount: 'Workspace MCP Cluster (3 servers active)',
    connectionsCount: 3,
    actions: [
      { id: 'call_tool', name: 'Call MCP Tool', description: 'Executes tool discovered on remote MCP server' },
      { id: 'read_resource', name: 'Read MCP Resource', description: 'Fetches resource URI content' },
    ],
    triggers: [],
  },

  // ==========================================
  // 11. STORAGE
  // ==========================================
  {
    id: 's3',
    name: 'Amazon S3',
    category: 'storage',
    icon: 'HardDrive',
    color: '#ff9900',
    authType: 'API_KEY',
    description: 'Store generated files, retrieve document assets, generate presigned download URLs, and archive logs.',
    verified: true,
    version: 'v2.1.0',
    status: 'disconnected',
    providerKey: 'S3',
    actions: [
      { id: 'put_object', name: 'Upload Object', description: 'Stores file in S3 bucket' },
      { id: 'get_object', name: 'Download Object', description: 'Fetches file content' },
      { id: 'generate_presigned_url', name: 'Create Presigned URL', description: 'Generates secure temporary download link' },
    ],
    triggers: [
      { id: 'object_created', name: 'Object Created in Bucket', description: 'Fires on S3 PutObject event' },
    ],
  },

  // ==========================================
  // 12. PAYMENTS & FINANCE
  // ==========================================
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    icon: 'CreditCard',
    color: '#635bff',
    authType: 'API_KEY',
    description: 'Process subscriptions, manage invoices, create payment intents, issue refunds, and listen to charge webhooks.',
    verified: true,
    version: 'v2024-06-20',
    status: 'disconnected',
    providerKey: 'STRIPE',
    actions: [
      { id: 'create_customer', name: 'Create Customer', description: 'Creates new Stripe customer record' },
      { id: 'create_payment_intent', name: 'Create Payment Intent', description: 'Initiates payment transaction' },
      { id: 'get_invoice', name: 'Get Invoice', description: 'Fetches invoice details and status' },
      { id: 'refund_charge', name: 'Refund Charge', description: 'Issues full or partial refund', permissionLevel: 'destructive', requiresConfirmation: true },
    ],
    triggers: [
      { id: 'payment_succeeded', name: 'Payment Succeeded', description: 'Fires when charge or payment intent succeeds' },
      { id: 'subscription_created', name: 'Subscription Created', description: 'Fires when new customer subscribes' },
      { id: 'invoice_payment_failed', name: 'Invoice Payment Failed', description: 'Fires when invoice charge fails' },
    ],
  },

  // ==========================================
  // 13. CUSTOMER SUPPORT
  // ==========================================
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'customer_support',
    icon: 'Headphones',
    color: '#03363d',
    authType: 'API_KEY',
    description: 'Create support tickets, update priority, assign to queues, add internal notes, and listen for incoming customer inquiries.',
    verified: true,
    version: 'v2.0',
    status: 'disconnected',
    providerKey: 'ZENDESK',
    actions: [
      { id: 'create_ticket', name: 'Create Ticket', description: 'Creates new support ticket' },
      { id: 'update_ticket', name: 'Update Ticket', description: 'Updates status, priority or assignee' },
      { id: 'add_comment', name: 'Add Ticket Comment', description: 'Adds public reply or private internal note' },
    ],
    triggers: [
      { id: 'ticket_created', name: 'Ticket Created', description: 'Fires on newly submitted customer ticket' },
      { id: 'ticket_solved', name: 'Ticket Solved', description: 'Fires when ticket resolution is confirmed' },
    ],
  },

  // ==========================================
  // 14. CUSTOM & INTERNAL API
  // ==========================================
  {
    id: 'custom_rest_api',
    name: 'Custom REST API',
    category: 'custom',
    icon: 'Code',
    color: '#0ea5e9',
    authType: 'CUSTOM',
    description: 'Connect any proprietary backend, internal microservice, GraphQL endpoint, or OpenAPI spec into the agent workflow.',
    verified: true,
    version: 'v1.0.0',
    status: 'connected',
    providerKey: 'CUSTOM_API',
    defaultAccount: 'Internal Core Service (https://api.internal.corp)',
    connectionsCount: 1,
    actions: [
      { id: 'call_endpoint', name: 'Call API Endpoint', description: 'Invokes configured endpoint with method and JSON payload' },
      { id: 'graphql_query', name: 'Execute GraphQL Query', description: 'Submits GraphQL query or mutation' },
    ],
    triggers: [
      { id: 'inbound_webhook', name: 'Custom Webhook Event', description: 'Receives signed HTTP POST webhook notifications' },
    ],
  },
];

/**
 * Universal helper to lookup connector metadata by any identifier
 */
export function getConnectorMeta(connectorId) {
  if (!connectorId) return null;
  const normalized = String(connectorId).toLowerCase().replace(/-/g, '_');
  return (
    CONNECTOR_CATALOG.find(
      (c) => c.id === connectorId || c.id === normalized || c.providerKey?.toLowerCase() === normalized
    ) || {
      id: connectorId,
      name: connectorId.charAt(0).toUpperCase() + connectorId.slice(1).replace(/_/g, ' '),
      color: '#3b82f6',
      icon: 'Boxes',
      category: 'custom',
    }
  );
}
