export const INITIAL_AGENTS = [
  {
    id: 'agent-buy-a-mac-system',
    name: 'Buy a Mac System',
    role: 'Hardware Procurement Specialist',
    description: 'Autonomous agent that researches Apple catalogs, compares M3/M4 chip benchmarks, verifies inventory, checks budget limits, and initiates confirmation-guarded purchases.',
    status: 'published',
    model: 'gpt-4o',
    provider: 'OpenAI',
    icon: 'Laptop',
    color: 'blue',
    systemPrompt: `You are the authorized Buy a Mac System procurement specialist for OneTab AI.
Your objectives:
1. Understand the user's workload requirements (Xcode build times, ML model inference, 4K video editing, or office productivity).
2. Query the authorized Apple product catalog and pricing APIs for Mac mini, Mac Studio, MacBook Air, and MacBook Pro models.
3. Compare chip tiers (M3/M4, Pro, Max) and unified memory requirements (16GB, 24GB, 36GB, 64GB, 128GB).
4. Verify stock and regional inventory across authorized enterprise suppliers.
5. Apply corporate budget limits (default $5,000 USD).
6. Before placing or booking any hardware order, trigger a mandatory purchase confirmation approval step.`,
    temperature: 0.2,
    maxTokens: 2048,
    memory: {
      type: 'hybrid',
      contextWindow: 16,
      retentionDays: 60,
      userSpecific: true,
      summarizeAfter: 10,
    },
    planning: {
      enabled: true,
      maxSteps: 10,
      budgetLimit: 5000.0,
      humanReviewOnTools: ['execute_purchase'],
    },
    tools: [
      'search_mac_catalog',
      'compare_specs',
      'check_inventory',
      'execute_purchase',
      'user_approval',
    ],
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-04-01T12:00:00Z',
    stats: {
      totalRuns: 348,
      successRate: 99.2,
      avgDuration: '1.8s',
      costEstimate: '$8.20',
    },
    deployment: {
      environments: ['production', 'staging', 'development'],
      widgetEnabled: true,
      publicLink: 'https://onetab.ai/agent/buy-a-mac-system',
      webhookUrl: 'https://api.onetab.ai/v1/agents/agent-buy-a-mac-system/webhook',
    },
    graphJson: JSON.stringify({
      nodes: [
        {
          id: 'start-1',
          type: 'START',
          position: { x: 80, y: 220 },
          data: {
            label: 'Hardware Procurement Request',
            subtitle: 'Triggered via widget, API, or chat',
            config: { triggerType: 'PROCUREMENT_INTENT' },
          },
        },
        {
          id: 'research-1',
          type: 'AGENT',
          position: { x: 380, y: 160 },
          data: {
            label: 'Mac Catalog & Spec Researcher',
            subtitle: 'Evaluates M3/M4 models and memory needs',
            config: {
              model: 'gpt-4o',
              temperature: 0.2,
              tools: ['search_mac_catalog', 'compare_specs'],
            },
          },
        },
        {
          id: 'inventory-1',
          type: 'AGENT',
          position: { x: 700, y: 160 },
          data: {
            label: 'Inventory & Pricing Verifier',
            subtitle: 'Checks supplier stock & budget compliance',
            config: {
              tools: ['check_inventory'],
            },
          },
        },
        {
          id: 'approval-1',
          type: 'USER_APPROVAL',
          position: { x: 1020, y: 160 },
          data: {
            label: 'Purchase Confirmation Guard',
            subtitle: 'Mandatory sign-off for financial transactions',
            config: {
              approverRole: 'Department Manager',
              actionName: 'execute_purchase',
              timeoutMinutes: 120,
            },
          },
        },
        {
          id: 'end-1',
          type: 'END',
          position: { x: 1340, y: 160 },
          data: {
            label: 'Order Confirmation & Receipt',
            subtitle: 'Sends tracking, PO number & summary',
            config: { channel: 'order_receipt' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'start-1', target: 'research-1', animated: true },
        { id: 'e2-3', source: 'research-1', target: 'inventory-1' },
        { id: 'e3-4', source: 'inventory-1', target: 'approval-1' },
        { id: 'e4-5', source: 'approval-1', target: 'end-1', animated: true },
      ],
    }),
  },
  {
    id: 'agent-support-pro',
    name: 'Customer Support Autonomous Concierge',
    role: 'Tier-1 Support Specialist',
    description: 'Resolves inbound customer inquiries, searches knowledge bases, verifies user entitlements, and escalates to human staff when needed.',
    status: 'published',
    model: 'gpt-4o',
    provider: 'OpenAI',
    systemPrompt: `You are a courteous, efficient Tier-1 Customer Support Specialist for OneTab AI.
Your objectives:
1. Understand the customer's problem thoroughly.
2. Search the knowledge base for relevant resolutions.
3. If an account modification or billing refund is requested, prepare an approval request for a human supervisor.
4. Always maintain a professional, concise, and helpful tone.`,
    temperature: 0.3,
    maxTokens: 2048,
    memory: {
      type: 'hybrid',
      contextWindow: 12,
      retentionDays: 30,
      userSpecific: true,
      summarizeAfter: 10,
    },
    planning: {
      enabled: true,
      maxSteps: 8,
      budgetLimit: 0.50,
      humanReviewOnTools: ['refund_charge', 'delete_account'],
    },
    tools: ['knowledge_search', 'slack_notify', 'create_ticket', 'user_approval'],
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-28T14:30:00Z',
    stats: {
      totalRuns: 1420,
      successRate: 98.4,
      avgDuration: '1.4s',
      costEstimate: '$18.42',
    },
    deployment: {
      environments: ['production', 'staging'],
      widgetEnabled: true,
      publicLink: 'https://onetab.ai/agent/support-pro',
      webhookUrl: 'https://api.onetab.ai/v1/agents/agent-support-pro/webhook',
    },
    graphJson: JSON.stringify({
      nodes: [
        {
          id: 'start-1',
          type: 'START',
          position: { x: 80, y: 220 },
          data: {
            label: 'Chat Message Received',
            subtitle: 'Triggered when customer sends query',
            config: { triggerType: 'CHAT_MESSAGE', channel: 'widget' },
          },
        },
        {
          id: 'intent-1',
          type: 'INTENT_CLASSIFIER',
          position: { x: 380, y: 200 },
          data: {
            label: 'Intent Classifier',
            subtitle: 'Classifies intent: FAQ, Billing, Bug',
            config: {
              model: 'gpt-4o-mini',
              categories: ['Technical FAQ', 'Billing / Refund', 'Report Bug', 'General Inquiries'],
            },
          },
        },
        {
          id: 'kb-search-1',
          type: 'KB_SEARCH',
          position: { x: 700, y: 120 },
          data: {
            label: 'Search Knowledge Base',
            subtitle: 'Semantic search on Support Docs',
            config: {
              knowledgeBaseId: 'kb-support-docs',
              topK: 4,
              minScore: 0.75,
            },
          },
        },
        {
          id: 'approval-1',
          type: 'USER_APPROVAL',
          position: { x: 700, y: 320 },
          data: {
            label: 'Billing Supervisor Approval',
            subtitle: 'Required for refund or subscription changes',
            config: {
              approverRole: 'Finance Admin',
              timeoutMinutes: 60,
              fallbackAction: 'ESCALATE_TICKET',
            },
          },
        },
        {
          id: 'llm-response-1',
          type: 'AGENT',
          position: { x: 1040, y: 200 },
          data: {
            label: 'Draft Support Response',
            subtitle: 'Synthesizes KB data & customer query',
            config: {
              model: 'gpt-4o',
              temperature: 0.3,
              systemPrompt: 'Provide a structured solution citing knowledge articles.',
            },
          },
        },
        {
          id: 'end-1',
          type: 'END',
          position: { x: 1360, y: 220 },
          data: {
            label: 'Send Reply to Customer',
            subtitle: 'Streams reply & prompts for feedback',
            config: { channel: 'chat_stream' },
          },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'start-1', target: 'intent-1', animated: true },
        { id: 'e2-3', source: 'intent-1', target: 'kb-search-1', label: 'FAQ / Info' },
        { id: 'e2-4', source: 'intent-1', target: 'approval-1', label: 'Refund / Account' },
        { id: 'e3-5', source: 'kb-search-1', target: 'llm-response-1' },
        { id: 'e4-5', source: 'approval-1', target: 'llm-response-1' },
        { id: 'e5-6', source: 'llm-response-1', target: 'end-1', animated: true },
      ],
    }),
  },
  {
    id: 'agent-firecrawl-research',
    name: 'Autonomous Web Intelligence & Market Analyst',
    role: 'Competitive Research Specialist',
    description: 'Crawls competitor websites using Firecrawl, extracts pricing, detects feature updates, and drafts a formatted markdown brief.',
    status: 'published',
    model: 'claude-3-5-sonnet',
    provider: 'Anthropic',
    systemPrompt: `You are an elite competitive intelligence analyst. Extract pricing tables, product feature changes, and positioning nuances with high precision.`,
    temperature: 0.2,
    maxTokens: 4096,
    tools: ['firecrawl_search', 'firecrawl_scrape', 'firecrawl_extract', 'slack_notify'],
    createdAt: '2026-03-15T09:00:00Z',
    updatedAt: '2026-03-29T11:20:00Z',
    stats: {
      totalRuns: 630,
      successRate: 99.1,
      avgDuration: '3.8s',
      costEstimate: '$24.10',
    },
    deployment: {
      environments: ['production'],
      widgetEnabled: false,
      webhookUrl: 'https://api.onetab.ai/v1/agents/agent-firecrawl-research/run',
    },
    graphJson: JSON.stringify({
      nodes: [
        {
          id: 'start-1',
          type: 'START',
          position: { x: 80, y: 200 },
          data: {
            label: 'Schedule Trigger',
            subtitle: 'Runs daily at 06:00 AM UTC',
            config: { triggerType: 'SCHEDULE', cron: '0 6 * * *' },
          },
        },
        {
          id: 'crawl-1',
          type: 'FIRECRAWL_SEARCH',
          position: { x: 380, y: 200 },
          data: {
            label: 'Firecrawl Search & Scrape',
            subtitle: 'Extracts competitor change logs',
            config: { query: 'AI Workflow builder pricing features 2026', limit: 5 },
          },
        },
        {
          id: 'extract-1',
          type: 'FIRECRAWL_EXTRACT',
          position: { x: 720, y: 200 },
          data: {
            label: 'Extract Structured JSON',
            subtitle: 'Extract pricing plans & features',
            config: { schema: 'PricingPlanSchema' },
          },
        },
        {
          id: 'agent-1',
          type: 'AGENT',
          position: { x: 1040, y: 200 },
          data: {
            label: 'Synthesize Executive Brief',
            subtitle: 'claude-3-5-sonnet',
            config: { model: 'claude-3-5-sonnet' },
          },
        },
        {
          id: 'slack-1',
          type: 'TOOL',
          position: { x: 1340, y: 200 },
          data: {
            label: 'Post to Slack #intel',
            subtitle: 'Sends formatted rich message',
            config: { channel: '#competitive-intel' },
          },
        },
        {
          id: 'end-1',
          type: 'END',
          position: { x: 1600, y: 200 },
          data: { label: 'Complete Execution', subtitle: 'Store report artifact' },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'start-1', target: 'crawl-1' },
        { id: 'e2-3', source: 'crawl-1', target: 'extract-1' },
        { id: 'e3-4', source: 'extract-1', target: 'agent-1' },
        { id: 'e4-5', source: 'agent-1', target: 'slack-1' },
        { id: 'e5-6', source: 'slack-1', target: 'end-1' },
      ],
    }),
  },
  {
    id: 'agent-code-reviewer',
    name: 'GitHub PR Quality & Security Auditor',
    role: 'Senior Staff Engineer Agent',
    description: 'Inspects incoming Pull Requests, evaluates architectural patterns, tests edge cases, scans for secrets, and posts actionable line comments.',
    status: 'draft',
    model: 'gemini-2-5-pro',
    provider: 'Google',
    systemPrompt: `You are a Principal Software Architect. Review code changes for security vulnerabilities, race conditions, memory leaks, and architectural anti-patterns.`,
    temperature: 0.1,
    maxTokens: 8192,
    tools: ['github_pr_read', 'github_comment', 'static_analysis'],
    createdAt: '2026-03-20T14:15:00Z',
    updatedAt: '2026-03-27T16:00:00Z',
    stats: {
      totalRuns: 88,
      successRate: 96.5,
      avgDuration: '2.9s',
      costEstimate: '$3.50',
    },
    deployment: {
      environments: ['development'],
      widgetEnabled: false,
    },
    graphJson: JSON.stringify({
      nodes: [
        {
          id: 'start-1',
          type: 'START',
          position: { x: 100, y: 200 },
          data: { label: 'GitHub PR Opened', subtitle: 'Webhook event trigger' },
        },
        {
          id: 'agent-1',
          type: 'AGENT',
          position: { x: 420, y: 200 },
          data: { label: 'Security & Diff Analyzer', subtitle: 'gemini-2-5-pro' },
        },
        {
          id: 'end-1',
          type: 'END',
          position: { x: 760, y: 200 },
          data: { label: 'Submit PR Review', subtitle: 'Approve or Request Changes' },
        },
      ],
      edges: [
        { id: 'e1-2', source: 'start-1', target: 'agent-1' },
        { id: 'e2-3', source: 'agent-1', target: 'end-1' },
      ],
    }),
  },
  {
    id: 'agent-lead-qualification',
    name: 'Inbound Sales Lead Qualifier & CRM Enrichment',
    role: 'Growth Operations Specialist',
    description: 'Scores inbound website signups using LinkedIn/Clearbit data, writes enriched contacts to HubSpot CRM, and schedules demos via Google Calendar.',
    status: 'published',
    model: 'gpt-4o',
    provider: 'OpenAI',
    systemPrompt: `Evaluate company size, tech stack, and ICP alignment. Score leads from 0 to 100 and route high-value enterprise leads to AE calendars.`,
    temperature: 0.2,
    maxTokens: 2048,
    tools: ['hubspot_create', 'clearbit_enrich', 'calendar_book', 'slack_notify'],
    createdAt: '2026-02-18T08:00:00Z',
    updatedAt: '2026-03-28T18:40:00Z',
    stats: {
      totalRuns: 890,
      successRate: 99.5,
      avgDuration: '1.8s',
      costEstimate: '$12.80',
    },
    deployment: {
      environments: ['production'],
      widgetEnabled: true,
      publicLink: 'https://onetab.ai/agent/lead-qualifier',
    },
    graphJson: null,
  },
];

export const INITIAL_MODELS = [
  {
    id: 'gpt-4o',
    name: 'OpenAI GPT-4o',
    provider: 'OpenAI',
    contextWindow: '128k',
    maxOutputTokens: 4096,
    inputPricePerMillion: '$2.50',
    outputPricePerMillion: '$10.00',
    latency: '380ms',
    capabilities: ['Structured Outputs', 'Tool Calling', 'Vision', 'Streaming'],
    recommended: true,
    available: true,
  },
  {
    id: 'gpt-4o-mini',
    name: 'OpenAI GPT-4o Mini',
    provider: 'OpenAI',
    contextWindow: '128k',
    maxOutputTokens: 16384,
    inputPricePerMillion: '$0.15',
    outputPricePerMillion: '$0.60',
    latency: '140ms',
    capabilities: ['Structured Outputs', 'Tool Calling', 'Streaming'],
    recommended: false,
    available: true,
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Anthropic Claude 3.5 Sonnet',
    provider: 'Anthropic',
    contextWindow: '200k',
    maxOutputTokens: 8192,
    inputPricePerMillion: '$3.00',
    outputPricePerMillion: '$15.00',
    latency: '420ms',
    capabilities: ['Complex Reasoning', 'Code Generation', 'Tool Calling', 'Artifacts'],
    recommended: true,
    available: true,
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Anthropic Claude 3.5 Haiku',
    provider: 'Anthropic',
    contextWindow: '200k',
    maxOutputTokens: 8192,
    inputPricePerMillion: '$0.80',
    outputPricePerMillion: '$4.00',
    latency: '180ms',
    capabilities: ['Fast Parsing', 'Tool Calling', 'Low Latency'],
    recommended: false,
    available: true,
  },
  {
    id: 'gemini-2-5-pro',
    name: 'Google Gemini 2.5 Pro',
    provider: 'Google',
    contextWindow: '1M',
    maxOutputTokens: 8192,
    inputPricePerMillion: '$1.25',
    outputPricePerMillion: '$5.00',
    latency: '310ms',
    capabilities: ['Massive Context', 'Multimodal', 'Code Execution', 'Tool Calling'],
    recommended: true,
    available: true,
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Google Gemini 2.5 Flash',
    provider: 'Google',
    contextWindow: '1M',
    maxOutputTokens: 8192,
    inputPricePerMillion: '$0.10',
    outputPricePerMillion: '$0.40',
    latency: '120ms',
    capabilities: ['Ultra Low Latency', 'High Throughput', 'Cost Effective'],
    recommended: false,
    available: true,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 (Reasoning)',
    provider: 'DeepSeek',
    contextWindow: '64k',
    maxOutputTokens: 8192,
    inputPricePerMillion: '$0.55',
    outputPricePerMillion: '$2.19',
    latency: '550ms',
    capabilities: ['Step-by-step CoT', 'Math & Logic', 'Autonomous Planning'],
    recommended: false,
    available: true,
  },
  {
    id: 'llama3:latest',
    name: 'Meta Llama 3.3 70B (Ollama / Local)',
    provider: 'Ollama (Local/Self-Hosted)',
    contextWindow: '128k',
    maxOutputTokens: 4096,
    inputPricePerMillion: 'Free ($0.00)',
    outputPricePerMillion: 'Free ($0.00)',
    latency: '90ms (Local GPU)',
    capabilities: ['Air-Gapped Execution', 'Zero Data Leakage', 'No API Costs'],
    recommended: false,
    available: true,
  },
];

export const INITIAL_INTEGRATIONS = [
  {
    id: 'int-firecrawl',
    name: 'Firecrawl Web Extraction',
    category: 'Search & Web Scraping',
    icon: 'Flame',
    description: 'Turn any website or web application into clean LLM-ready markdown or structured JSON schemas.',
    status: 'connected',
    verified: true,
    version: 'v1.4.2',
    authType: 'API_KEY',
    connectedAccount: 'api_key_****98xL',
    toolsCount: 4,
    usage: '1,280 requests this month',
  },
  {
    id: 'int-slack',
    name: 'Slack Bot & Channels',
    category: 'Communication',
    icon: 'MessageSquare',
    description: 'Send alerts, handle interactive buttons, trigger agents from #channel mentions, and request approvals.',
    status: 'connected',
    verified: true,
    version: 'v2.1.0',
    authType: 'OAUTH2',
    connectedAccount: 'OneTab Workspace Bot',
    toolsCount: 6,
    usage: '4,120 events processed',
  },
  {
    id: 'int-gmail',
    name: 'Gmail & Google Workspace',
    category: 'Productivity',
    icon: 'Mail',
    description: 'Draft replies, read incoming threads, categorize emails, and manage message labels.',
    status: 'connected',
    verified: true,
    version: 'v3.0.1',
    authType: 'OAUTH2',
    connectedAccount: 'support@onetab.ai',
    toolsCount: 5,
    usage: '680 emails sent',
  },
  {
    id: 'int-hubspot',
    name: 'HubSpot CRM',
    category: 'Sales & CRM',
    icon: 'Users',
    description: 'Create and update contacts, deals, company associations, and track sales pipeline activities.',
    status: 'connected',
    verified: true,
    version: 'v1.8.0',
    authType: 'API_KEY',
    connectedAccount: 'HubSpot Pro (ID: 884102)',
    toolsCount: 8,
    usage: '940 leads synced',
  },
  {
    id: 'int-postgres',
    name: 'PostgreSQL Database',
    category: 'Database & Storage',
    icon: 'Database',
    description: 'Execute parameterized queries, read relational schemas, insert audit logs, and trigger event listeners.',
    status: 'connected',
    verified: true,
    version: 'v16.2',
    authType: 'CONNECTION_STRING',
    connectedAccount: 'pg-main-cluster:5432/app',
    toolsCount: 3,
    usage: '12,400 queries run',
  },
  {
    id: 'int-github',
    name: 'GitHub Enterprise',
    category: 'Developer Tools',
    icon: 'GitPullRequest',
    description: 'Read repositories, inspect PR diffs, create commits, post reviews, and trigger CI checks.',
    status: 'connected',
    verified: true,
    version: 'v3.1.2',
    authType: 'PERSONAL_ACCESS_TOKEN',
    connectedAccount: 'onetab-bot (Admin)',
    toolsCount: 7,
    usage: '340 PRs reviewed',
  },
  {
    id: 'int-jira',
    name: 'Atlassian Jira',
    category: 'Project Management',
    icon: 'CheckSquare',
    description: 'Create tickets, advance sprints, auto-assign developers, and sync issue statuses.',
    status: 'disconnected',
    verified: true,
    version: 'v2.0.0',
    authType: 'OAUTH2',
    toolsCount: 6,
    usage: 'Not configured',
  },
  {
    id: 'int-linear',
    name: 'Linear Issue Tracker',
    category: 'Project Management',
    icon: 'Bookmark',
    description: 'Ultra-fast software development issue tracking, cycle automations, and triage workflows.',
    status: 'connected',
    verified: true,
    version: 'v1.1.0',
    authType: 'API_KEY',
    connectedAccount: 'Linear Org: OneTab',
    toolsCount: 5,
    usage: '110 issues synced',
  },
  {
    id: 'int-s3',
    name: 'Amazon S3 / Cloud Storage',
    category: 'Storage',
    icon: 'HardDrive',
    description: 'Read and write binary files, PDF archives, user uploads, and generated reports.',
    status: 'connected',
    verified: true,
    version: 'v2.4.0',
    authType: 'AWS_KEYS',
    connectedAccount: 's3://onetab-ai-assets-prod',
    toolsCount: 4,
    usage: '45 GB stored',
  },
  {
    id: 'int-stripe',
    name: 'Stripe Payments',
    category: 'Finance',
    icon: 'CreditCard',
    description: 'Look up customer invoices, verify subscription tiers, and issue supervisor-approved refunds.',
    status: 'connected',
    verified: true,
    version: 'v2024-11',
    authType: 'API_KEY',
    connectedAccount: 'acct_1NZx... (Live Mode)',
    toolsCount: 5,
    usage: '540 events verified',
  },
  {
    id: 'int-teams',
    name: 'Microsoft Teams',
    category: 'Communication',
    icon: 'Send',
    description: 'Send Adaptive Cards, notify incident response channels, and receive team replies.',
    status: 'disconnected',
    verified: true,
    version: 'v1.0.0',
    authType: 'OAUTH2',
    toolsCount: 4,
    usage: 'Not configured',
  },
  {
    id: 'int-salesforce',
    name: 'Salesforce CRM',
    category: 'Sales & CRM',
    icon: 'Cloud',
    description: 'Enterprise pipeline management, Lead conversion, Opportunity forecasting and SOQL querying.',
    status: 'disconnected',
    verified: true,
    version: 'v58.0',
    authType: 'OAUTH2',
    toolsCount: 9,
    usage: 'Not configured',
  },
];

export const INITIAL_KNOWLEDGE_BASES = [
  {
    id: 'kb-support-docs',
    name: 'Customer Support Knowledge Base & SOPs',
    description: 'Official product documentation, troubleshooting manuals, billing refund protocols, and escalation policies.',
    totalDocuments: 48,
    totalChunks: 2420,
    embeddingModel: 'text-embedding-3-small',
    vectorStore: 'Qdrant (Hybrid Search)',
    lastIndexed: '2026-03-29T10:15:00Z',
    status: 'READY',
    sources: [
      { id: 'src-1', name: 'Product_Handbook_v4.2.pdf', type: 'PDF', size: '4.8 MB', chunks: 840, status: 'INDEXED' },
      { id: 'src-2', name: 'Billing_Refund_Guidelines.docx', type: 'DOCX', size: '1.2 MB', chunks: 190, status: 'INDEXED' },
      { id: 'src-3', name: 'https://docs.onetab.ai/troubleshooting', type: 'WEB_CRAWL', size: '42 pages', chunks: 980, status: 'INDEXED' },
      { id: 'src-4', name: 'Security_Compliance_FAQ.txt', type: 'TXT', size: '450 KB', chunks: 410, status: 'INDEXED' },
    ],
  },
  {
    id: 'kb-engineering-runbooks',
    name: 'Engineering Runbooks & Architecture Specs',
    description: 'Internal infrastructure deployment guides, database failover runbooks, API contracts, and security policies.',
    totalDocuments: 22,
    totalChunks: 1350,
    embeddingModel: 'text-embedding-3-large',
    vectorStore: 'Qdrant (Hybrid Search)',
    lastIndexed: '2026-03-27T16:00:00Z',
    status: 'READY',
    sources: [
      { id: 'src-5', name: 'Database_Disaster_Recovery.md', type: 'MARKDOWN', size: '320 KB', chunks: 260, status: 'INDEXED' },
      { id: 'src-6', name: 'Kubernetes_Cluster_Spec.pdf', type: 'PDF', size: '6.1 MB', chunks: 1090, status: 'INDEXED' },
    ],
  },
  {
    id: 'kb-sales-playbook',
    name: 'Enterprise Sales & Objection Handling Playbook',
    description: 'Competitor comparison matrix, pricing tier battlecards, customer references, and ROI calculators.',
    totalDocuments: 14,
    totalChunks: 680,
    embeddingModel: 'text-embedding-3-small',
    vectorStore: 'Qdrant (Keyword + Vector)',
    lastIndexed: '2026-03-25T11:00:00Z',
    status: 'READY',
    sources: [
      { id: 'src-7', name: 'Battlecard_Competitors_2026.pdf', type: 'PDF', size: '3.4 MB', chunks: 450, status: 'INDEXED' },
      { id: 'src-8', name: 'Pricing_Discount_Matrix.csv', type: 'CSV', size: '180 KB', chunks: 230, status: 'INDEXED' },
    ],
  },
];

export const INITIAL_EXECUTIONS = [
  {
    id: 'exec-8941',
    agentId: 'agent-support-pro',
    agentName: 'Customer Support Autonomous Concierge',
    workflowName: 'Inbound Ticket Resolution Flow',
    trigger: 'CHAT_MESSAGE',
    status: 'SUCCESS',
    startedAt: '2026-03-29T11:42:10Z',
    completedAt: '2026-03-29T11:42:12Z',
    durationMs: 1420,
    tokensUsed: 1240,
    costEstimated: '$0.0094',
    promptText: 'Customer inquired: "How can I enable single sign-on with Okta on my enterprise plan?"',
    resultSummary: 'Identified SSO documentation in Knowledge Base, provided step-by-step SAML guide, verified user tier.',
    steps: [
      { id: 'step-1', nodeName: 'Chat Message Received', status: 'SUCCESS', durationMs: 40, output: { message: 'How can I enable SSO?' } },
      { id: 'step-2', nodeName: 'Intent Classifier', status: 'SUCCESS', durationMs: 210, output: { intent: 'Technical FAQ', confidence: 0.98 } },
      { id: 'step-3', nodeName: 'Search Knowledge Base', status: 'SUCCESS', durationMs: 380, output: { articlesFound: 3, topScore: 0.94 } },
      { id: 'step-4', nodeName: 'Draft Support Response', status: 'SUCCESS', durationMs: 720, output: { text: 'To configure Okta SSO, navigate to Workspace Settings > Security > SAML...' } },
      { id: 'step-5', nodeName: 'Send Reply to Customer', status: 'SUCCESS', durationMs: 70, output: { delivered: true } },
    ],
  },
  {
    id: 'exec-8940',
    agentId: 'agent-firecrawl-research',
    agentName: 'Autonomous Web Intelligence & Market Analyst',
    workflowName: 'Scheduled Daily Competitor Crawl',
    trigger: 'SCHEDULE',
    status: 'SUCCESS',
    startedAt: '2026-03-29T06:00:00Z',
    completedAt: '2026-03-29T06:00:04Z',
    durationMs: 3840,
    tokensUsed: 3950,
    costEstimated: '$0.0382',
    promptText: 'Daily automated crawl of 5 target competitor product blogs.',
    resultSummary: 'Scraped 5 sites, detected 2 new feature releases, posted summary alert to #competitive-intel.',
    steps: [
      { id: 'step-1', nodeName: 'Schedule Trigger', status: 'SUCCESS', durationMs: 10, output: { cron: '0 6 * * *' } },
      { id: 'step-2', nodeName: 'Firecrawl Search & Scrape', status: 'SUCCESS', durationMs: 1850, output: { crawledUrls: 5, bytesRead: '142KB' } },
      { id: 'step-3', nodeName: 'Extract Structured JSON', status: 'SUCCESS', durationMs: 620, output: { updatesDetected: 2 } },
      { id: 'step-4', nodeName: 'Synthesize Executive Brief', status: 'SUCCESS', durationMs: 1200, output: { reportLength: '450 words' } },
      { id: 'step-5', nodeName: 'Post to Slack #intel', status: 'SUCCESS', durationMs: 160, output: { channel: '#competitive-intel', ts: '1774771204.01' } },
    ],
  },
  {
    id: 'exec-8939',
    agentId: 'agent-support-pro',
    agentName: 'Customer Support Autonomous Concierge',
    workflowName: 'Inbound Ticket Resolution Flow',
    trigger: 'CHAT_MESSAGE',
    status: 'WAITING_APPROVAL',
    startedAt: '2026-03-29T10:14:00Z',
    durationMs: 820,
    tokensUsed: 640,
    costEstimated: '$0.0041',
    promptText: 'Customer requested: "$240 refund for accidental team seat upgrade on invoice #INV-9921."',
    resultSummary: 'Paused execution at human approval checkpoint. Awaiting finance supervisor sign-off.',
    steps: [
      { id: 'step-1', nodeName: 'Chat Message Received', status: 'SUCCESS', durationMs: 30, output: { message: 'Need refund for invoice #INV-9921' } },
      { id: 'step-2', nodeName: 'Intent Classifier', status: 'SUCCESS', durationMs: 190, output: { intent: 'Billing / Refund', confidence: 0.99 } },
      { id: 'step-3', nodeName: 'Billing Supervisor Approval', status: 'WAITING', durationMs: 600, output: { approvalId: 'appr-301', requestedAmount: '$240.00' } },
    ],
  },
  {
    id: 'exec-8938',
    agentId: 'agent-code-reviewer',
    agentName: 'GitHub PR Quality & Security Auditor',
    workflowName: 'PR Security Scan',
    trigger: 'WEBHOOK',
    status: 'FAILED',
    startedAt: '2026-03-28T22:30:00Z',
    completedAt: '2026-03-28T22:30:02Z',
    durationMs: 1920,
    tokensUsed: 890,
    costEstimated: '$0.0072',
    promptText: 'GitHub Webhook: pull_request.opened on repo onetab/backend-core #412',
    resultSummary: 'Rate limit exceeded on external static analysis linter. Automatic retry attempted twice.',
    steps: [
      { id: 'step-1', nodeName: 'GitHub PR Opened', status: 'SUCCESS', durationMs: 50, output: { pr: 412 } },
      { id: 'step-2', nodeName: 'Security & Diff Analyzer', status: 'FAILED', durationMs: 1870, output: { error: 'Static linter service 429 Too Many Requests: retry after 60s' } },
    ],
  },
];

export const INITIAL_APPROVALS = [
  {
    id: 'appr-301',
    executionId: 'exec-8939',
    agentId: 'agent-support-pro',
    agentName: 'Customer Support Autonomous Concierge',
    title: 'Customer Refund Request ($240.00)',
    description: 'Customer requested refund for accidental seat allocation on Invoice #INV-9921. Customer tier: Pro Annual.',
    category: 'FINANCIAL_TRANSACTION',
    status: 'PENDING',
    priority: 'HIGH',
    requestedBy: 'AI Support Concierge',
    assignedTo: 'Finance Admin Team',
    createdAt: '2026-03-29T10:14:00Z',
    deadline: '2026-03-29T18:00:00Z',
    proposedPayload: {
      action: 'stripe.refunds.create',
      chargeId: 'ch_3NzK81928371',
      amount: '$240.00',
      reason: 'requested_by_customer',
      customerEmail: 'sarah.connor@acme-corp.io',
    },
  },
  {
    id: 'appr-300',
    executionId: 'exec-8910',
    agentId: 'agent-lead-qualification',
    agentName: 'Inbound Sales Lead Qualifier',
    title: 'VIP Account Executive Demo Assignment',
    description: 'Fortune 500 prospect (Coca-Cola Beverages, 8,000 seats) requested enterprise trial and migration assistance.',
    category: 'CUSTOMER_ESCALATION',
    status: 'APPROVED',
    priority: 'URGENT',
    requestedBy: 'Lead Qualification Agent',
    assignedTo: 'VP of Sales',
    createdAt: '2026-03-28T15:20:00Z',
    decidedAt: '2026-03-28T15:35:00Z',
    decidedBy: 'Marcus Vance (VP Sales)',
    decisionComment: 'Fast-tracked to Strategic Enterprise AE team.',
  },
  {
    id: 'appr-299',
    executionId: 'exec-8895',
    agentId: 'agent-code-reviewer',
    agentName: 'GitHub PR Quality Auditor',
    title: 'Bypass Production Security Warning for Hotfix PR #409',
    description: 'PR modifies OAuth token refresh logic. AI agent flagged potential race condition on distributed Redis locks.',
    category: 'SECURITY_EXCEPTION',
    status: 'REJECTED',
    priority: 'CRITICAL',
    requestedBy: 'Developer (via PR Bot)',
    assignedTo: 'Security Lead',
    createdAt: '2026-03-27T19:10:00Z',
    decidedAt: '2026-03-27T19:40:00Z',
    decidedBy: 'Elena Rostova (Head of SecOps)',
    decisionComment: 'Cannot bypass. Fix the distributed lock acquisition timeout before merging.',
  },
];

export const INITIAL_ANALYTICS = {
  summary: {
    totalExecutions: 3028,
    successfulExecutions: 2955,
    failedExecutions: 48,
    pendingApprovals: 25,
    successRate: 97.6,
    avgLatencyMs: 1480,
    totalTokens: '4.8M',
    totalCost: '$58.82',
    activeAgentsCount: 4,
  },
  timeSeries: [
    { date: 'Mar 23', runs: 320, success: 314, failed: 6, tokens: 420000, cost: 5.2 },
    { date: 'Mar 24', runs: 380, success: 372, failed: 8, tokens: 490000, cost: 6.1 },
    { date: 'Mar 25', runs: 450, success: 442, failed: 8, tokens: 680000, cost: 8.4 },
    { date: 'Mar 26', runs: 410, success: 401, failed: 9, tokens: 590000, cost: 7.3 },
    { date: 'Mar 27', runs: 490, success: 482, failed: 8, tokens: 730000, cost: 9.1 },
    { date: 'Mar 28', runs: 520, success: 512, failed: 8, tokens: 810000, cost: 10.2 },
    { date: 'Mar 29', runs: 458, success: 448, failed: 10, tokens: 710000, cost: 8.8 },
  ],
  modelsBreakdown: [
    { name: 'OpenAI GPT-4o', share: 48, calls: 1450, cost: '$28.40' },
    { name: 'Claude 3.5 Sonnet', share: 28, calls: 840, cost: '$21.10' },
    { name: 'Google Gemini 2.5 Pro', share: 14, calls: 420, cost: '$6.20' },
    { name: 'GPT-4o Mini', share: 10, calls: 318, cost: '$3.12' },
  ],
};

export const INITIAL_VARIABLES = [
  { id: 'v-1', key: 'WORKSPACE_SLUG', scope: 'WORKSPACE', type: 'string', value: 'enterprise-ai-lab', isSecret: false },
  { id: 'v-2', key: 'DEFAULT_SUPPORT_EMAIL', scope: 'GLOBAL', type: 'string', value: 'support@onetab.ai', isSecret: false },
  { id: 'v-3', key: 'MAX_REFUND_LIMIT_USD', scope: 'GLOBAL', type: 'number', value: '500', isSecret: false },
  { id: 'v-4', key: 'FIRECRAWL_API_SECRET', scope: 'ENVIRONMENT', type: 'secret', value: 'fc_live_9921...masked', isSecret: true },
  { id: 'v-5', key: 'SLACK_NOTIFY_WEBHOOK', scope: 'ENVIRONMENT', type: 'secret', value: 'https://hooks.slack.com/services/...', isSecret: true },
];

export const INITIAL_COLLABORATORS = [
  { id: 'col-1', name: 'Alex Rivera', email: 'alex@onetab.ai', role: 'Workspace Owner', status: 'active', avatar: '' },
  { id: 'col-2', name: 'Sophia Chen', email: 'sophia@onetab.ai', role: 'Agent Builder', status: 'active', avatar: '' },
  { id: 'col-3', name: 'Liam Davies', email: 'liam@onetab.ai', role: 'Developer', status: 'active', avatar: '' },
  { id: 'col-4', name: 'Elena Rostova', email: 'elena@onetab.ai', role: 'Administrator', status: 'active', avatar: '' },
  { id: 'col-5', name: 'Marcus Vance', email: 'marcus@onetab.ai', role: 'Operator', status: 'active', avatar: '' },
];
