// Complete 80+ node catalog across 8 categories with schemas and validation rules for AI Agent Studio

export const NODE_CATEGORIES = [
  { id: 'triggers', label: 'Triggers', icon: 'Zap', description: 'Events that initiate workflow execution' },
  { id: 'ai', label: 'AI & Reasoning', icon: 'Bot', description: 'LLMs, classifiers, extractors & agents' },
  { id: 'knowledge', label: 'Knowledge & RAG', icon: 'BookOpen', description: 'Vector search, documents & rerankers' },
  { id: 'logic', label: 'Logic & Flow', icon: 'GitBranch', description: 'Branches, loops, routers & delay' },
  { id: 'transform', label: 'Data & Transform', icon: 'Sliders', description: 'Formatting, expressions, parsing & variables' },
  { id: 'tools', label: 'Tools & Integrations', icon: 'Wrench', description: 'HTTP, Firecrawl, MCP & databases' },
  { id: 'human', label: 'Human in the Loop', icon: 'UserCheck', description: 'Approvals, reviews & user input' },
  { id: 'output', label: 'Outputs & Responses', icon: 'CheckCircle2', description: 'Chat response, webhook & database write' },
];

export const NODE_CATALOG = [
  // ==========================================
  // 1. TRIGGERS (Module 3.1)
  // ==========================================
  {
    type: 'TRIGGER_MANUAL',
    category: 'triggers',
    label: 'Manual Trigger',
    subtitle: 'Run on demand',
    icon: 'Play',
    color: 'emerald',
    description: 'Triggered manually by a user in the UI, testing console, or API dashboard.',
    inputs: [],
    outputs: [{ name: 'payload', type: 'object', description: 'Manual input parameters' }],
    defaultConfig: { allowCustomInput: true, inputSchema: '{\n  "query": "string"\n}' },
  },
  {
    type: 'TRIGGER_CHAT',
    category: 'triggers',
    label: 'Chat Message Trigger',
    subtitle: 'User sends a message',
    icon: 'MessageSquare',
    color: 'emerald',
    description: 'Triggered when a user sends a message in a widget, portal, or Slack thread.',
    inputs: [],
    outputs: [
      { name: 'message', type: 'string', description: 'User prompt text' },
      { name: 'sessionId', type: 'string', description: 'Conversation session UUID' },
      { name: 'userProfile', type: 'object', description: 'Authenticated user info' },
    ],
    defaultConfig: { channel: 'all', streamResponses: true, welcomeGreeting: 'Hi, how can I help you today?' },
  },
  {
    type: 'TRIGGER_FORM',
    category: 'triggers',
    label: 'Form Submission Trigger',
    subtitle: 'Web form intake',
    icon: 'FileText',
    color: 'emerald',
    description: 'Fired when an end-user submits an embedded web form or lead intake survey.',
    inputs: [],
    outputs: [{ name: 'formData', type: 'object', description: 'Submitted form fields' }],
    defaultConfig: { formId: 'lead-intake-form', validateCaptcha: true },
  },
  {
    type: 'TRIGGER_SCHEDULE',
    category: 'triggers',
    label: 'Schedule Trigger',
    subtitle: 'Cron / Interval timer',
    icon: 'Clock',
    color: 'emerald',
    description: 'Runs periodically on a defined cron schedule or fixed time interval.',
    inputs: [],
    outputs: [
      { name: 'scheduledTime', type: 'string', description: 'ISO execution timestamp' },
      { name: 'runId', type: 'string', description: 'Scheduled execution ID' },
    ],
    defaultConfig: { cron: '0 9 * * 1-5', timezone: 'UTC', enabled: true },
  },
  {
    type: 'TRIGGER_WEBHOOK',
    category: 'triggers',
    label: 'Webhook Trigger',
    subtitle: 'Inbound HTTP POST / GET',
    icon: 'Globe',
    color: 'emerald',
    description: 'Listens for external HTTP webhooks from Stripe, GitHub, Shopify, etc.',
    inputs: [],
    outputs: [
      { name: 'body', type: 'object', description: 'Parsed request body' },
      { name: 'headers', type: 'object', description: 'HTTP request headers' },
      { name: 'query', type: 'object', description: 'URL query params' },
    ],
    defaultConfig: { httpMethod: 'POST', authRequired: true, secretToken: 'whsec_auto' },
  },
  {
    type: 'TRIGGER_API',
    category: 'triggers',
    label: 'API Request Trigger',
    subtitle: 'Programmatic API trigger',
    icon: 'Code2',
    color: 'emerald',
    description: 'Dedicated REST endpoint callable with an Agent Studio API key.',
    inputs: [],
    outputs: [{ name: 'body', type: 'object', description: 'Incoming JSON payload' }],
    defaultConfig: { endpointPath: '/v1/run', rateLimitPerMinute: 60 },
  },
  {
    type: 'TRIGGER_APP_EVENT',
    category: 'triggers',
    label: 'App Event Trigger',
    subtitle: 'Platform event listener',
    icon: 'Activity',
    color: 'emerald',
    description: 'Triggered by events inside OneTab Platform (e.g. document created, deal updated).',
    inputs: [],
    outputs: [{ name: 'eventData', type: 'object', description: 'Platform event payload' }],
    defaultConfig: { eventType: 'document.created', filterExpression: '' },
  },
  {
    type: 'TRIGGER_DB_EVENT',
    category: 'triggers',
    label: 'Database Event Trigger',
    subtitle: 'CDC / Table row inserted',
    icon: 'Database',
    color: 'emerald',
    description: 'Monitors database change streams for newly inserted, updated, or deleted rows.',
    inputs: [],
    outputs: [{ name: 'record', type: 'object', description: 'Database row change delta' }],
    defaultConfig: { connectionId: 'pg-main', table: 'users', action: 'INSERT' },
  },
  {
    type: 'TRIGGER_EMAIL',
    category: 'triggers',
    label: 'Email Received Trigger',
    subtitle: 'Inbound email webhook',
    icon: 'Mail',
    color: 'emerald',
    description: 'Triggers when a new email arrives in a monitored mailbox or forwarding alias.',
    inputs: [],
    outputs: [
      { name: 'sender', type: 'string', description: 'From address' },
      { name: 'subject', type: 'string', description: 'Email subject line' },
      { name: 'body', type: 'string', description: 'Email plain text / HTML body' },
      { name: 'attachments', type: 'array', description: 'Attached files' },
    ],
    defaultConfig: { mailboxAddress: 'support@agent.onetab.ai', parseAttachments: true },
  },
  {
    type: 'APP_CONNECTOR_TRIGGER',
    category: 'triggers',
    label: 'App Connector Trigger',
    subtitle: 'Event from connected SaaS app',
    icon: 'Boxes',
    color: 'emerald',
    description: 'Fires when an external event occurs in a connected app (Teams, Slack, Gmail, GitHub, etc.).',
    inputs: [],
    outputs: [
      { name: 'eventPayload', type: 'object', description: 'Full event payload received from the app' },
      { name: 'connectorId', type: 'string', description: 'Unique connector identifier' },
      { name: 'triggerId', type: 'string', description: 'Trigger event type identifier' },
    ],
    defaultConfig: {
      connectorId: 'microsoft-teams',
      connectionId: 'default',
      triggerId: 'new_message',
      pollInterval: 60,
    },
  },
  {
    type: 'TEAMS_TRIGGER_MESSAGE',
    category: 'triggers',
    label: 'Teams New Message Trigger',
    subtitle: 'Microsoft Teams event',
    icon: 'MessageSquare',
    color: 'emerald',
    description: 'Triggers when a new message is posted or the bot is mentioned in Microsoft Teams.',
    inputs: [],
    outputs: [
      { name: 'message', type: 'string', description: 'Content of the message' },
      { name: 'sender', type: 'string', description: 'User who sent the message' },
      { name: 'teamId', type: 'string', description: 'Microsoft Teams Team ID' },
      { name: 'channelId', type: 'string', description: 'Channel ID where message was posted' },
      { name: 'rawEvent', type: 'object', description: 'Raw Microsoft Graph webhook event' },
    ],
    defaultConfig: {
      connectorId: 'microsoft-teams',
      connectionId: 'conn-ms-teams-corp',
      triggerId: 'new_message',
      filter: 'all_messages',
    },
  },
  {
    type: 'TRIGGER_AGENT',
    category: 'triggers',
    label: 'Agent-to-Agent Trigger',
    subtitle: 'Delegated from supervisor',
    icon: 'Sparkles',
    color: 'emerald',
    description: 'Fires when another parent or supervisor agent delegates a sub-task.',
    inputs: [],
    outputs: [
      { name: 'parentAgentId', type: 'string', description: 'Originating agent UUID' },
      { name: 'taskContext', type: 'object', description: 'Delegated context & parameters' },
    ],
    defaultConfig: { allowedCallers: ['*'], timeoutSeconds: 120 },
  },

  // ==========================================
  // 2. AI & REASONING (Module 3.2)
  // ==========================================
  {
    type: 'AGENT',
    category: 'ai',
    label: 'Autonomous AI Agent',
    subtitle: 'Autonomous goal reasoner',
    icon: 'Bot',
    color: 'purple',
    description: 'Autonomous reasoning engine that selects tools, manages sub-tasks, and iterates towards a goal.',
    inputs: [{ name: 'prompt', type: 'string', description: 'Task instruction or user message' }],
    outputs: [
      { name: 'result', type: 'string', description: 'Final agent synthesis' },
      { name: 'steps', type: 'array', description: 'Trace of tool calls and actions' },
    ],
    defaultConfig: {
      model: 'gpt-4o',
      temperature: 0.3,
      maxSteps: 6,
      systemPrompt: 'You are an intelligent specialist agent.',
      tools: ['firecrawl_search', 'kb_search'],
    },
  },
  {
    type: 'SUB_AGENT',
    category: 'ai',
    label: 'Specialist Sub-Agent',
    subtitle: 'Dedicated task delegate',
    icon: 'Sparkles',
    color: 'purple',
    description: 'Worker agent focused on a specific narrow domain (e.g. Code Reviewer, Fact Checker).',
    inputs: [{ name: 'subTask', type: 'string', description: 'Specific directive' }],
    outputs: [{ name: 'output', type: 'string', description: 'Specialist output' }],
    defaultConfig: { role: 'Researcher', model: 'gpt-4o-mini', temperature: 0.2 },
  },
  {
    type: 'AGENT_COORDINATOR',
    category: 'ai',
    label: 'Multi-Agent Coordinator',
    subtitle: 'Supervisor swarm manager',
    icon: 'Network',
    color: 'purple',
    description: 'Coordinates execution across multiple specialist agents, aggregating their conclusions.',
    inputs: [{ name: 'goal', type: 'string', description: 'High-level business objective' }],
    outputs: [
      { name: 'finalConsensus', type: 'string', description: 'Combined consensus answer' },
      { name: 'agentOutputs', type: 'object', description: 'Individual worker deliverables' },
    ],
    defaultConfig: { strategy: 'hierarchical', maxIterations: 5 },
  },
  {
    type: 'AI_CHAT_MODEL',
    category: 'ai',
    label: 'LLM / Chat Model',
    subtitle: 'Direct language model call',
    icon: 'Cpu',
    color: 'purple',
    description: 'Executes a direct prompt or message history through any supported foundation model.',
    inputs: [
      { name: 'messages', type: 'array', description: 'Chat history' },
      { name: 'systemPrompt', type: 'string', description: 'Optional system override' },
    ],
    outputs: [{ name: 'response', type: 'string', description: 'Generated text' }],
    defaultConfig: { model: 'gpt-4o', temperature: 0.7, maxTokens: 2048 },
  },
  {
    type: 'INTENT_CLASSIFIER',
    category: 'ai',
    label: 'Intent Classifier',
    subtitle: 'Categorize user intent',
    icon: 'Layers',
    color: 'purple',
    description: 'Classifies input text into predefined categories for conditional routing.',
    inputs: [{ name: 'text', type: 'string', description: 'Text to analyze' }],
    outputs: [
      { name: 'intent', type: 'string', description: 'Highest scoring category' },
      { name: 'confidence', type: 'number', description: 'Confidence score (0 - 1)' },
    ],
    defaultConfig: { categories: ['Support', 'Sales', 'Billing', 'General'] },
  },
  {
    type: 'STRUCTURED_OUTPUT',
    category: 'ai',
    label: 'Structured Output Generator',
    subtitle: 'Strict JSON Schema output',
    icon: 'Code',
    color: 'purple',
    description: 'Enforces strict JSON schema generation using native model tool/structured formats.',
    inputs: [{ name: 'input', type: 'string', description: 'Unstructured source text' }],
    outputs: [{ name: 'json', type: 'object', description: 'Validated JSON object' }],
    defaultConfig: { schemaName: 'CustomSchema', schemaDefinition: '{\n  "summary": "string",\n  "sentiment": "string"\n}' },
  },
  {
    type: 'AI_SUMMARIZER',
    category: 'ai',
    label: 'Summarizer',
    subtitle: 'Condense long documents',
    icon: 'AlignLeft',
    color: 'purple',
    description: 'Generates concise bullet points, executive summaries, or key takeaways.',
    inputs: [{ name: 'content', type: 'string', description: 'Text or document content' }],
    outputs: [{ name: 'summary', type: 'string', description: 'Structured summary' }],
    defaultConfig: { length: 'concise', format: 'bullet_points' },
  },
  {
    type: 'AI_TRANSLATOR',
    category: 'ai',
    label: 'AI Translator',
    subtitle: 'Multi-language localization',
    icon: 'Globe',
    color: 'purple',
    description: 'Translates text or markdown into any target language with cultural nuance.',
    inputs: [{ name: 'text', type: 'string', description: 'Source text' }],
    outputs: [{ name: 'translated', type: 'string', description: 'Localized text' }],
    defaultConfig: { targetLanguage: 'Spanish', preserveFormatting: true },
  },
  {
    type: 'AI_SENTIMENT',
    category: 'ai',
    label: 'Sentiment & Emotion',
    subtitle: 'Tone & sentiment score',
    icon: 'Sparkles',
    color: 'purple',
    description: 'Analyzes user sentiment, urgency level, and customer satisfaction score.',
    inputs: [{ name: 'text', type: 'string', description: 'Customer message' }],
    outputs: [
      { name: 'sentiment', type: 'string', description: 'Positive / Neutral / Negative' },
      { name: 'score', type: 'number', description: 'Float between -1.0 and +1.0' },
      { name: 'urgency', type: 'string', description: 'Low / Medium / High' },
    ],
    defaultConfig: { detectUrgency: true },
  },
  {
    type: 'AI_ENTITY_EXTRACTOR',
    category: 'ai',
    label: 'Entity Extractor (NER)',
    subtitle: 'Extract names, dates, amounts',
    icon: 'Search',
    color: 'purple',
    description: 'Extracts named entities such as people, organizations, dates, order IDs, and currencies.',
    inputs: [{ name: 'text', type: 'string', description: 'Source text' }],
    outputs: [{ name: 'entities', type: 'array', description: 'Array of detected entities' }],
    defaultConfig: { entityTypes: ['Person', 'Organization', 'Email', 'Money', 'Date'] },
  },
  {
    type: 'PROMPT_TEMPLATE',
    category: 'ai',
    label: 'Prompt Template',
    subtitle: 'Interpolate variables into prompt',
    icon: 'FileCode',
    color: 'purple',
    description: 'Constructs dynamic prompts using variable interpolation `{{var}}`.',
    inputs: [{ name: 'variables', type: 'object', description: 'Values for variables' }],
    outputs: [{ name: 'prompt', type: 'string', description: 'Compiled prompt string' }],
    defaultConfig: { template: 'Review the following customer inquiry from {{customer.name}}:\n{{input.message}}' },
  },
  {
    type: 'AI_GUARDRAIL',
    category: 'ai',
    label: 'AI Guardrails & Validator',
    subtitle: 'Safety, PII & injection check',
    icon: 'Shield',
    color: 'purple',
    description: 'Scans prompts and model outputs for prompt injection, toxic language, and PII leakage.',
    inputs: [{ name: 'text', type: 'string', description: 'Text to inspect' }],
    outputs: [
      { name: 'passed', type: 'boolean', description: 'True if no safety violation' },
      { name: 'sanitizedText', type: 'string', description: 'Text with PII redacted' },
    ],
    defaultConfig: { blockPromptInjection: true, redactPII: true, failFast: false },
  },
  {
    type: 'MODEL_ROUTER',
    category: 'ai',
    label: 'Model Router & Fallback',
    subtitle: 'Route by complexity & cost',
    icon: 'Split',
    color: 'purple',
    description: 'Dynamically routes simple requests to fast/cheap models and hard tasks to flagship models.',
    inputs: [{ name: 'prompt', type: 'string', description: 'User input' }],
    outputs: [{ name: 'selectedModel', type: 'string', description: 'Chosen model identifier' }],
    defaultConfig: { primaryModel: 'gpt-4o-mini', complexModel: 'gpt-4o', fallbackModel: 'claude-3-5-sonnet' },
  },

  // ==========================================
  // 3. KNOWLEDGE & RETRIEVAL (Module 3.3)
  // ==========================================
  {
    type: 'KB_SEARCH',
    category: 'knowledge',
    label: 'Knowledge Base Search',
    subtitle: 'Semantic & Hybrid RAG',
    icon: 'Search',
    color: 'cyan',
    description: 'Queries vector database collections to retrieve top-k semantically relevant chunks.',
    inputs: [{ name: 'query', type: 'string', description: 'Search query string' }],
    outputs: [
      { name: 'chunks', type: 'array', description: 'Retrieved text chunks' },
      { name: 'citations', type: 'array', description: 'Source document references' },
    ],
    defaultConfig: { knowledgeBaseId: 'kb-support-docs', topK: 4, minScore: 0.75, searchMode: 'hybrid' },
  },
  {
    type: 'DOC_RETRIEVAL',
    category: 'knowledge',
    label: 'Document Loader',
    subtitle: 'Fetch file from cloud / URL',
    icon: 'FileText',
    color: 'cyan',
    description: 'Loads document content from S3, Google Drive, or URL for runtime parsing.',
    inputs: [{ name: 'fileUrl', type: 'string', description: 'File location' }],
    outputs: [{ name: 'rawText', type: 'string', description: 'Extracted plain text' }],
    defaultConfig: { extractTables: true, ocrEnabled: true },
  },
  {
    type: 'RERANKER',
    category: 'knowledge',
    label: 'Context Reranker',
    subtitle: 'Cohere / Cross-encoder rerank',
    icon: 'BarChart2',
    color: 'cyan',
    description: 'Reorders retrieved search results using cross-encoder relevance models.',
    inputs: [{ name: 'chunks', type: 'array', description: 'Initial search chunks' }],
    outputs: [{ name: 'rankedChunks', type: 'array', description: 'Reranked top results' }],
    defaultConfig: { topK: 3, model: 'cohere-rerank-v3' },
  },
  {
    type: 'CONTEXT_BUILDER',
    category: 'knowledge',
    label: 'Context Assembler',
    subtitle: 'Format RAG context window',
    icon: 'Layers',
    color: 'cyan',
    description: 'Formats retrieved chunks, citations, and metadata into a clean context section for prompts.',
    inputs: [{ name: 'chunks', type: 'array', description: 'Retrieved chunks' }],
    outputs: [{ name: 'contextString', type: 'string', description: 'Formatted context block' }],
    defaultConfig: { maxTokens: 4000, includeCitations: true },
  },
  {
    type: 'TEXT_SPLITTER',
    category: 'knowledge',
    label: 'Text Chunker & Splitter',
    subtitle: 'Recursive chunk splitting',
    icon: 'Scissors',
    color: 'cyan',
    description: 'Splits raw documents into chunk tokens with sliding window overlap.',
    inputs: [{ name: 'documentText', type: 'string', description: 'Full document text' }],
    outputs: [{ name: 'chunks', type: 'array', description: 'Array of chunks' }],
    defaultConfig: { chunkSize: 512, chunkOverlap: 64, strategy: 'recursive' },
  },

  // ==========================================
  // 4. LOGIC & CONTROL FLOW (Module 3.4)
  // ==========================================
  {
    type: 'IF_ELSE',
    category: 'logic',
    label: 'If / Else Branch',
    subtitle: 'Conditional path split',
    icon: 'GitBranch',
    color: 'amber',
    description: 'Evaluates a boolean condition to route execution to True or False handles.',
    inputs: [{ name: 'condition', type: 'any', description: 'Expression or variable' }],
    outputs: [
      { name: 'true', type: 'flow', description: 'Path taken if condition is met' },
      { name: 'false', type: 'flow', description: 'Path taken otherwise' },
    ],
    defaultConfig: { operator: 'equals', valueA: '', valueB: '' },
  },
  {
    type: 'SWITCH_CASE',
    category: 'logic',
    label: 'Switch / Router',
    subtitle: 'Multi-way conditional route',
    icon: 'Split',
    color: 'amber',
    description: 'Matches an input value against multiple cases and branches accordingly.',
    inputs: [{ name: 'input', type: 'string', description: 'Value to test' }],
    outputs: [
      { name: 'case1', type: 'flow', description: 'Match 1' },
      { name: 'case2', type: 'flow', description: 'Match 2' },
      { name: 'default', type: 'flow', description: 'Default fallback' },
    ],
    defaultConfig: { cases: ['High', 'Medium', 'Low'] },
  },
  {
    type: 'PARALLEL_SPLIT',
    category: 'logic',
    label: 'Parallel Execution',
    subtitle: 'Fork parallel branches',
    icon: 'GitFork',
    color: 'amber',
    description: 'Forks execution into multiple simultaneous parallel branches to reduce latency.',
    inputs: [],
    outputs: [
      { name: 'branchA', type: 'flow', description: 'Parallel lane 1' },
      { name: 'branchB', type: 'flow', description: 'Parallel lane 2' },
    ],
    defaultConfig: { waitForAll: true },
  },
  {
    type: 'MERGE_PATHS',
    category: 'logic',
    label: 'Merge / Join',
    subtitle: 'Recombine parallel paths',
    icon: 'GitMerge',
    color: 'amber',
    description: 'Waits for parallel branches to complete and merges their outputs into an aggregated map.',
    inputs: [
      { name: 'pathA', type: 'any', description: 'Output from branch A' },
      { name: 'pathB', type: 'any', description: 'Output from branch B' },
    ],
    outputs: [{ name: 'merged', type: 'object', description: 'Combined results' }],
    defaultConfig: { mode: 'combine_object' },
  },
  {
    type: 'LOOP',
    category: 'logic',
    label: 'For Each Loop',
    subtitle: 'Iterate over array items',
    icon: 'Repeat',
    color: 'amber',
    description: 'Iterates through each element in an array and runs child workflow nodes.',
    inputs: [{ name: 'items', type: 'array', description: 'Array of elements' }],
    outputs: [
      { name: 'item', type: 'any', description: 'Current item' },
      { name: 'index', type: 'number', description: 'Current index' },
    ],
    defaultConfig: { batchSize: 1, parallel: false },
  },
  {
    type: 'WAIT_DELAY',
    category: 'logic',
    label: 'Wait / Delay',
    subtitle: 'Pause flow for duration',
    icon: 'Hourglass',
    color: 'amber',
    description: 'Pauses execution for a specified number of seconds or until a specific timestamp.',
    inputs: [],
    outputs: [{ name: 'resumedAt', type: 'string', description: 'Resume timestamp' }],
    defaultConfig: { delaySeconds: 5 },
  },
  {
    type: 'RETRY_NODE',
    category: 'logic',
    label: 'Retry with Backoff',
    subtitle: 'Resilient fault tolerance',
    icon: 'RefreshCw',
    color: 'amber',
    description: 'Retries downstream actions on error using exponential backoff.',
    inputs: [{ name: 'action', type: 'flow', description: 'Node to retry' }],
    outputs: [{ name: 'result', type: 'any', description: 'Successful execution result' }],
    defaultConfig: { maxRetries: 3, backoffMultiplier: 2, initialDelayMs: 1000 },
  },
  {
    type: 'ERROR_HANDLER',
    category: 'logic',
    label: 'Error Handler (Catch)',
    subtitle: 'Graceful failure recovery',
    icon: 'AlertTriangle',
    color: 'amber',
    description: 'Catches runtime exceptions in upstream nodes and routes to a fallback path.',
    inputs: [],
    outputs: [
      { name: 'error', type: 'object', description: 'Caught error message and stack' },
      { name: 'fallback', type: 'flow', description: 'Fallback execution branch' },
    ],
    defaultConfig: { notifyOnCatch: true },
  },
  {
    type: 'STOP_WORKFLOW',
    category: 'logic',
    label: 'Stop Workflow',
    subtitle: 'Early exit condition',
    icon: 'StopCircle',
    color: 'amber',
    description: 'Terminates workflow execution immediately with a custom reason or status.',
    inputs: [],
    outputs: [],
    defaultConfig: { reason: 'Condition not satisfied', status: 'cancelled' },
  },

  // ==========================================
  // 5. DATA TRANSFORMATION (Module 3.5)
  // ==========================================
  {
    type: 'SET_VARIABLE',
    category: 'transform',
    label: 'Set Variable',
    subtitle: 'Assign workflow state',
    icon: 'Variable',
    color: 'blue',
    description: 'Stores or transforms values in the workflow or session execution state.',
    inputs: [{ name: 'value', type: 'any', description: 'Data to store' }],
    outputs: [{ name: 'stored', type: 'any', description: 'Variable reference' }],
    defaultConfig: { variableName: 'myVar', scope: 'workflow' },
  },
  {
    type: 'GET_VARIABLE',
    category: 'transform',
    label: 'Get Variable',
    subtitle: 'Read workflow / env state',
    icon: 'Variable',
    color: 'blue',
    description: 'Retrieves a variable stored in session, workflow, or environment scopes.',
    inputs: [],
    outputs: [{ name: 'value', type: 'any', description: 'Stored value' }],
    defaultConfig: { variableName: 'myVar', defaultValue: '' },
  },
  {
    type: 'DATA_MAPPER',
    category: 'transform',
    label: 'Map Data & Fields',
    subtitle: 'Transform object schema',
    icon: 'Sliders',
    color: 'blue',
    description: 'Maps fields from one object schema to another using key-value mappings.',
    inputs: [{ name: 'source', type: 'object', description: 'Source object' }],
    outputs: [{ name: 'mapped', type: 'object', description: 'New mapped object' }],
    defaultConfig: { mappingRules: [{ sourceField: 'first_name', targetField: 'firstName' }] },
  },
  {
    type: 'DATA_FILTER',
    category: 'transform',
    label: 'Filter & Sort Array',
    subtitle: 'Filter collection items',
    icon: 'Filter',
    color: 'blue',
    description: 'Filters array elements by conditions and sorts by ascending/descending keys.',
    inputs: [{ name: 'array', type: 'array', description: 'Input list' }],
    outputs: [{ name: 'filtered', type: 'array', description: 'Cleaned array' }],
    defaultConfig: { filterCondition: 'item.active === true', sortKey: 'createdAt', sortOrder: 'desc' },
  },
  {
    type: 'CODE_JAVASCRIPT',
    category: 'transform',
    label: 'Code (JavaScript)',
    subtitle: 'Custom data transform logic',
    icon: 'Code2',
    color: 'blue',
    description: 'Executes lightweight sandboxed JavaScript for formatting, mapping, or math.',
    inputs: [{ name: 'input', type: 'any', description: 'Input variables object' }],
    outputs: [{ name: 'output', type: 'any', description: 'Returned script value' }],
    defaultConfig: { code: '// Access inputs via input\nreturn {\n  success: true,\n  timestamp: Date.now()\n};' },
  },
  {
    type: 'CODE_PYTHON',
    category: 'transform',
    label: 'Code (Python)',
    subtitle: 'Python 3 data script',
    icon: 'Terminal',
    color: 'blue',
    description: 'Executes sandboxed Python script for scientific computation, data cleansing, or Pandas tasks.',
    inputs: [{ name: 'input', type: 'any', description: 'Input arguments dict' }],
    outputs: [{ name: 'output', type: 'any', description: 'Script result' }],
    defaultConfig: { code: '# Access inputs via input_dict\nreturn {"processed": True, "count": len(input_dict.keys())}' },
  },
  {
    type: 'JSON_PARSE',
    category: 'transform',
    label: 'JSON Parse / Serialize',
    subtitle: 'Convert string to JSON',
    icon: 'FileCode',
    color: 'blue',
    description: 'Parses JSON strings into objects or stringifies JavaScript data structures.',
    inputs: [{ name: 'data', type: 'any', description: 'Input string or object' }],
    outputs: [{ name: 'result', type: 'any', description: 'Transformed data' }],
    defaultConfig: { mode: 'parse' },
  },
  {
    type: 'DATE_FORMATTER',
    category: 'transform',
    label: 'Date & Time Formatter',
    subtitle: 'Parse & format dates',
    icon: 'Calendar',
    color: 'blue',
    description: 'Converts timestamps between timezones, relative formats, and ISO strings.',
    inputs: [{ name: 'date', type: 'string', description: 'Timestamp string' }],
    outputs: [{ name: 'formattedDate', type: 'string', description: 'Formatted string' }],
    defaultConfig: { outputFormat: 'YYYY-MM-DD HH:mm:ss', targetTimezone: 'America/New_York' },
  },

  // ==========================================
  // 6. TOOLS & INTEGRATIONS (Module 3.6)
  // ==========================================
  {
    type: 'HTTP_REQUEST',
    category: 'tools',
    label: 'HTTP Request (REST)',
    subtitle: 'Call external REST API',
    icon: 'Globe',
    color: 'orange',
    description: 'Makes generic HTTP GET, POST, PUT, DELETE requests with headers & body.',
    inputs: [{ name: 'body', type: 'object', description: 'Request payload' }],
    outputs: [
      { name: 'responseBody', type: 'object', description: 'HTTP response body' },
      { name: 'statusCode', type: 'number', description: 'Status code (e.g. 200)' },
    ],
    defaultConfig: { method: 'GET', url: 'https://api.example.com/v1/resource', headers: {} },
  },
  {
    type: 'FIRECRAWL_SEARCH',
    category: 'tools',
    label: 'Firecrawl Search',
    subtitle: 'Web search & markdown crawl',
    icon: 'Flame',
    color: 'orange',
    description: 'Search the live web and receive sanitized markdown pages for AI synthesis.',
    inputs: [{ name: 'query', type: 'string', description: 'Search terms' }],
    outputs: [{ name: 'results', type: 'array', description: 'Markdown web pages' }],
    defaultConfig: { limit: 3, scrapeOptions: { formats: ['markdown'] } },
  },
  {
    type: 'FIRECRAWL_EXTRACT',
    category: 'tools',
    label: 'Firecrawl Extract',
    subtitle: 'Extract structured data from URL',
    icon: 'Flame',
    color: 'orange',
    description: 'Crawls a specific website and extracts structured fields matching your schema.',
    inputs: [{ name: 'url', type: 'string', description: 'Target URL' }],
    outputs: [{ name: 'extractedJson', type: 'object', description: 'Structured JSON' }],
    defaultConfig: { prompt: 'Extract pricing, feature tiers, and FAQs' },
  },
  {
    type: 'MCP_TOOL',
    category: 'tools',
    label: 'MCP Tool Action',
    subtitle: 'Model Context Protocol',
    icon: 'Plug',
    color: 'orange',
    description: 'Calls a tool registered on a connected Model Context Protocol (MCP) server.',
    inputs: [{ name: 'parameters', type: 'object', description: 'Tool input arguments' }],
    outputs: [{ name: 'toolResult', type: 'any', description: 'MCP server response' }],
    defaultConfig: { serverName: 'Default MCP', toolName: 'search_database' },
  },
  {
    type: 'DB_QUERY',
    category: 'tools',
    label: 'Database Query (SQL)',
    subtitle: 'Postgres / MySQL / Mongo',
    icon: 'Database',
    color: 'orange',
    description: 'Executes a parameterized SQL query or Mongo find operation against a connected database.',
    inputs: [{ name: 'params', type: 'object', description: 'SQL binding parameters' }],
    outputs: [
      { name: 'rows', type: 'array', description: 'Query results' },
      { name: 'rowCount', type: 'number', description: 'Number of rows returned' },
    ],
    defaultConfig: { connectionId: 'pg-prod', query: 'SELECT * FROM users WHERE active = true LIMIT 50' },
  },
  {
    type: 'SLACK_SEND',
    category: 'tools',
    label: 'Slack / Teams Message',
    subtitle: 'Post channel alert',
    icon: 'MessageSquare',
    color: 'orange',
    description: 'Sends rich notifications or interactive approval blocks to Slack or Microsoft Teams.',
    inputs: [{ name: 'message', type: 'string', description: 'Message markdown text' }],
    outputs: [{ name: 'messageId', type: 'string', description: 'Slack message timestamp ID' }],
    defaultConfig: { channel: '#agent-alerts', asBot: true },
  },
  {
    type: 'EMAIL_SEND',
    category: 'tools',
    label: 'Transactional Email Action',
    subtitle: 'Centralized email send',
    icon: 'Mail',
    color: 'orange',
    description: 'Dispatches reliable transactional emails via the platform Email Service using template keys or custom content.',
    inputs: [
      { name: 'to', type: 'string', description: 'Recipient email address' },
      { name: 'templateKey', type: 'string', description: 'Template key (e.g. AGENT_APPROVAL_REQUIRED, AGENT_EXECUTION_COMPLETED)' },
      { name: 'templateData', type: 'object', description: 'Dynamic variables for the template' },
      { name: 'subject', type: 'string', description: 'Custom subject override (optional)' },
      { name: 'html', type: 'string', description: 'Custom HTML body override (optional)' },
    ],
    outputs: [
      { name: 'sentMessageId', type: 'string', description: 'Dispatch UUID' },
      { name: 'delivered', type: 'boolean', description: 'Delivery success status' },
    ],
    defaultConfig: {
      templateKey: 'AGENT_RESULT_AVAILABLE',
      useCentralizedService: true,
      from: 'notifications@agent.onetab.ai',
    },
  },
  {
    type: 'APP_CONNECTOR_ACTION',
    category: 'tools',
    label: 'App Connector Action',
    subtitle: 'Execute SaaS app action',
    icon: 'Boxes',
    color: 'orange',
    description: 'Executes an authenticated action against any configured App Connector (Teams, Slack, Gmail, GitHub, Jira, etc.).',
    inputs: [{ name: 'input', type: 'object', description: 'Action input parameters' }],
    outputs: [
      { name: 'result', type: 'any', description: 'Action execution response data' },
      { name: 'success', type: 'boolean', description: 'Execution status flag' },
    ],
    defaultConfig: {
      connectorId: 'microsoft-teams',
      connectionId: 'default',
      actionId: 'send_channel_message',
      input: {
        teamId: '',
        channelId: '',
        message: '{{agent.output}}',
      },
    },
  },
  {
    type: 'TEAMS_SEND_MESSAGE',
    category: 'tools',
    label: 'Teams Send Message',
    subtitle: 'Microsoft Teams channel/DM',
    icon: 'MessageSquare',
    color: 'orange',
    description: 'Post formatted rich text or agent response directly into a Microsoft Teams channel or direct message.',
    inputs: [
      { name: 'message', type: 'string', description: 'Message body or markdown' },
      { name: 'teamId', type: 'string', description: 'Target Microsoft Team' },
      { name: 'channelId', type: 'string', description: 'Target Teams Channel' },
    ],
    outputs: [
      { name: 'messageId', type: 'string', description: 'Dispatched message ID' },
      { name: 'webUrl', type: 'string', description: 'Teams message deep link' },
    ],
    defaultConfig: {
      connectorId: 'microsoft-teams',
      connectionId: 'conn-ms-teams-corp',
      actionId: 'send_channel_message',
      teamId: 'team-eng-core',
      channelId: 'general',
      message: '{{agent.output}}',
    },
  },
  {
    type: 'TEAMS_CREATE_MEETING',
    category: 'tools',
    label: 'Teams Schedule Meeting',
    subtitle: 'Microsoft Teams calendar',
    icon: 'Calendar',
    color: 'orange',
    description: 'Creates an online Microsoft Teams meeting invite with join URL and audio details.',
    inputs: [
      { name: 'subject', type: 'string', description: 'Meeting title' },
      { name: 'startTime', type: 'string', description: 'Start time ISO string' },
      { name: 'endTime', type: 'string', description: 'End time ISO string' },
      { name: 'attendees', type: 'array', description: 'Attendee email addresses' },
    ],
    outputs: [
      { name: 'meetingId', type: 'string', description: 'Created meeting ID' },
      { name: 'joinWebUrl', type: 'string', description: 'Online meeting join link' },
    ],
    defaultConfig: {
      connectorId: 'microsoft-teams',
      connectionId: 'conn-ms-teams-corp',
      actionId: 'create_meeting',
      subject: 'AI Agent Consultation',
      durationMinutes: 30,
    },
  },

  // ==========================================
  // 7. HUMAN INTERACTION (Module 3.7)
  // ==========================================
  {
    type: 'USER_APPROVAL',
    category: 'human',
    label: 'Human Approval Checkpoint',
    subtitle: 'Pause for team sign-off',
    icon: 'UserCheck',
    color: 'rose',
    description: 'Pauses workflow execution and creates an approval request in the Approval Center.',
    inputs: [{ name: 'details', type: 'object', description: 'Action details to approve' }],
    outputs: [
      { name: 'approved', type: 'boolean', description: 'Sign-off decision' },
      { name: 'decisionComment', type: 'string', description: 'Reviewer comments' },
    ],
    defaultConfig: { approverRole: 'Finance Admin', timeoutHours: 24, allowRejectionFallback: true },
  },
  {
    type: 'HUMAN_INPUT',
    category: 'human',
    label: 'Ask User Question',
    subtitle: 'Request missing information',
    icon: 'HelpCircle',
    color: 'rose',
    description: 'Prompts the human user to provide clarifying inputs before continuing the flow.',
    inputs: [{ name: 'question', type: 'string', description: 'Prompt to display' }],
    outputs: [{ name: 'answer', type: 'string', description: 'User provided input' }],
    defaultConfig: { question: 'Please enter the purchase order confirmation number:' },
  },
  {
    type: 'HUMAN_REVIEW',
    category: 'human',
    label: 'Review & Edit AI Output',
    subtitle: 'Human-in-the-loop editing',
    icon: 'Edit3',
    color: 'rose',
    description: 'Presents draft AI output to a human reviewer to modify or accept before publishing.',
    inputs: [{ name: 'draftContent', type: 'string', description: 'AI generated draft' }],
    outputs: [{ name: 'finalContent', type: 'string', description: 'Human edited output' }],
    defaultConfig: { autoApproveAfterHours: 0 },
  },
  {
    type: 'ESCALATE_HUMAN',
    category: 'human',
    label: 'Escalate to Human Agent',
    subtitle: 'Hand off live session',
    icon: 'Headphones',
    color: 'rose',
    description: 'Transfers live chat session to Zendesk, Intercom, or human support team with context summary.',
    inputs: [{ name: 'summary', type: 'string', description: 'Conversation brief' }],
    outputs: [{ name: 'ticketId', type: 'string', description: 'Created support ticket ID' }],
    defaultConfig: { priority: 'high', queue: 'Tier 2 Support' },
  },

  // ==========================================
  // 8. OUTPUTS (Module 3.8)
  // ==========================================
  {
    type: 'END',
    category: 'output',
    label: 'Workflow Output',
    subtitle: 'Final result delivery',
    icon: 'CheckCircle2',
    color: 'emerald',
    description: 'Completes the workflow execution and delivers the final output to the caller.',
    inputs: [{ name: 'outputData', type: 'any', description: 'Final response data' }],
    outputs: [],
    defaultConfig: { deliveryFormat: 'json' },
  },
  {
    type: 'CHAT_RESPONSE',
    category: 'output',
    label: 'Chat Response Stream',
    subtitle: 'Send streaming text to user',
    icon: 'MessageSquare',
    color: 'emerald',
    description: 'Streams AI answer markdown, citations, and follow-up prompt pills back to chat user.',
    inputs: [{ name: 'reply', type: 'string', description: 'Bot text' }],
    outputs: [],
    defaultConfig: { stream: true, renderMarkdown: true },
  },
  {
    type: 'WEBHOOK_RESPONSE',
    category: 'output',
    label: 'Webhook Response',
    subtitle: 'Reply to incoming HTTP call',
    icon: 'Send',
    color: 'emerald',
    description: 'Returns a custom HTTP status code and response body to the webhook caller.',
    inputs: [{ name: 'response', type: 'object', description: 'HTTP reply payload' }],
    outputs: [],
    defaultConfig: { statusCode: 200, contentType: 'application/json' },
  },
  {
    type: 'DB_WRITE',
    category: 'output',
    label: 'Database Write / Upsert',
    subtitle: 'Persist record to database',
    icon: 'Database',
    color: 'emerald',
    description: 'Inserts or updates rows in PostgreSQL, MongoDB, or Snowflake.',
    inputs: [{ name: 'record', type: 'object', description: 'Data to persist' }],
    outputs: [{ name: 'insertedId', type: 'string', description: 'New record primary key' }],
    defaultConfig: { table: 'audit_log', operation: 'insert' },
  },
  {
    type: 'RETURN_TO_PARENT',
    category: 'output',
    label: 'Return Result to Parent Agent',
    subtitle: 'Sub-workflow deliverable',
    icon: 'CornerUpLeft',
    color: 'emerald',
    description: 'Yields the execution output back to the invoking supervisor or parent agent workflow.',
    inputs: [{ name: 'result', type: 'any', description: 'Deliverable' }],
    outputs: [],
    defaultConfig: {},
  },
];
