-- Catches up the entire compliance subgraph (15 tables: ComplianceRegion,
-- ComplianceCountry, CompliancePlatform, ComplianceDistribution,
-- ComplianceAppVersion, CompliancePolicy, ComplianceRequirement,
-- ComplianceRequirementScope, ComplianceReview, ComplianceChecklistItem,
-- ComplianceIssue, ComplianceEvidence, ComplianceReleaseOverride,
-- ComplianceAuditLog, ComplianceLegalLink) which has been in schema.prisma
-- with no corresponding migration since it was added — every one of these
-- tables was missing from the database. `ComplianceService.seedOfficialGuidelines()`
-- was silently catching the resulting Prisma error on every API boot
-- ("Compliance seeding skipped or failed"), so the whole compliance module
-- has never actually worked against a real database.
--
-- Generated via `prisma migrate diff --from-config-datasource
-- --to-schema prisma/schema.prisma --script` against the live dev database,
-- then hand-wrapped in the idempotent IF NOT EXISTS / DO-block-guarded style
-- already used by this repo's other hand-written migrations (`prisma migrate
-- dev` is broken here — see repo history).
--
-- Also includes two unrelated, harmless index renames the same diff surfaced
-- (autogenerated names truncated at Postgres's 63-byte identifier limit).
--
-- The diff also proposed `ALTER COLUMN "searchVector" DROP DEFAULT` on 5
-- unrelated tables (channels/projects/tasks/uploads/work_documents) —
-- `prisma migrate diff` mis-reads those as ordinary columns with a stale
-- default, but they're actually `GENERATED ALWAYS AS (...) STORED` columns
-- in the live database, and Postgres refuses `DROP DEFAULT` on a generated
-- column (`ERROR 42601`). That statement failing is what "compliance-
-- subgraph drift + searchVector" refers to in this repo's history — left out
-- here entirely since the columns already are what schema.prisma wants; this
-- migration only needs to fix the actually-missing compliance tables.

-- CreateEnum
DO $$ BEGIN
  CREATE TYPE "CompliancePlatformType" AS ENUM ('WEB', 'DESKTOP', 'MOBILE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceSeverity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceCategory" AS ENUM ('PRIVACY', 'DATA_COLLECTION', 'USER_CONSENT', 'ACCOUNT_DELETION', 'AUTHENTICATION', 'PAYMENTS', 'CONTENT_MODERATION', 'SECURITY', 'PERMISSIONS', 'NOTIFICATIONS', 'TRACKING_ADVERTISING', 'AGE_RATING', 'METADATA_ASSETS', 'LEGAL_TERMS', 'REGIONAL_LEGAL', 'EXPORT_COMPLIANCE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceChecklistStatus" AS ENUM ('PASSED', 'FAILED', 'WARNING', 'SKIPPED', 'NOT_APPLICABLE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceReviewStatus" AS ENUM ('IN_PROGRESS', 'READY_FOR_SUBMISSION', 'BLOCKED', 'APPROVED', 'RELEASED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceIssueStatus" AS ENUM ('OPEN', 'INVESTIGATING', 'FIX_REQUIRED', 'IN_PROGRESS', 'READY_FOR_RESUBMISSION', 'SUBMITTED', 'RESOLVED', 'ACCEPTED', 'WONT_FIX');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "ComplianceIssueSource" AS ENUM ('STORE_REVIEW', 'INTERNAL_AUDIT', 'AUTOMATED_SCAN', 'REGULATORY_NOTICE');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
  CREATE TYPE "CompliancePolicyStatus" AS ENUM ('DRAFT', 'ACTIVE', 'UNDER_REVIEW', 'DEPRECATED');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_regions" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_regions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_countries" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "regionId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_countries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_platforms" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "CompliancePlatformType" NOT NULL DEFAULT 'DESKTOP',
    "currentVersion" TEXT NOT NULL DEFAULT '1.0.0',
    "minSupportedVersion" TEXT NOT NULL DEFAULT '1.0.0',
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_platforms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_distributions" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "platformId" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_distributions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_app_versions" (
    "id" TEXT NOT NULL,
    "platformId" TEXT NOT NULL,
    "version" TEXT NOT NULL,
    "releaseDate" TIMESTAMP(3),
    "status" "ComplianceReviewStatus" NOT NULL DEFAULT 'IN_PROGRESS',
    "isCurrent" BOOLEAN NOT NULL DEFAULT false,
    "changelog" TEXT,
    "metadata" TEXT NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_app_versions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_policies" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "version" TEXT NOT NULL DEFAULT '1.0.0',
    "effectiveDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewDate" TIMESTAMP(3),
    "status" "CompliancePolicyStatus" NOT NULL DEFAULT 'ACTIVE',
    "externalGuidelineRef" TEXT,
    "externalGuidelineUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_policies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_requirements" (
    "id" TEXT NOT NULL,
    "policyId" TEXT,
    "code" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" "ComplianceCategory" NOT NULL,
    "severity" "ComplianceSeverity" NOT NULL DEFAULT 'MEDIUM',
    "isBlocking" BOOLEAN NOT NULL DEFAULT false,
    "defaultStatus" "ComplianceChecklistStatus" NOT NULL DEFAULT 'WARNING',
    "remediationGuide" TEXT,
    "externalUrl" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_requirements_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_requirement_scopes" (
    "id" TEXT NOT NULL,
    "requirementId" TEXT NOT NULL,
    "countryId" TEXT,
    "regionId" TEXT,
    "platformId" TEXT,
    "distributionId" TEXT,
    "minVersion" TEXT,
    "maxVersion" TEXT,
    "isExcluded" BOOLEAN NOT NULL DEFAULT false,
    "overrideSeverity" "ComplianceSeverity",
    "overrideNotes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_requirement_scopes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_reviews" (
    "id" TEXT NOT NULL,
    "appVersionId" TEXT NOT NULL,
    "platformId" TEXT NOT NULL,
    "distributionId" TEXT,
    "countryId" TEXT,
    "status" "ComplianceReviewStatus" NOT NULL DEFAULT 'IN_PROGRESS',
    "overallScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "passedCount" INTEGER NOT NULL DEFAULT 0,
    "failedCount" INTEGER NOT NULL DEFAULT 0,
    "warningCount" INTEGER NOT NULL DEFAULT 0,
    "blockedCount" INTEGER NOT NULL DEFAULT 0,
    "totalCount" INTEGER NOT NULL DEFAULT 0,
    "summary" TEXT,
    "reviewerNotes" TEXT,
    "submittedAt" TIMESTAMP(3),
    "reviewedAt" TIMESTAMP(3),
    "reviewerId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_checklist_items" (
    "id" TEXT NOT NULL,
    "reviewId" TEXT NOT NULL,
    "requirementId" TEXT NOT NULL,
    "status" "ComplianceChecklistStatus" NOT NULL DEFAULT 'WARNING',
    "notes" TEXT,
    "assignedToId" TEXT,
    "dueDate" TIMESTAMP(3),
    "verifiedAt" TIMESTAMP(3),
    "verifiedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_checklist_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_issues" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "category" "ComplianceCategory" NOT NULL,
    "severity" "ComplianceSeverity" NOT NULL DEFAULT 'HIGH',
    "status" "ComplianceIssueStatus" NOT NULL DEFAULT 'OPEN',
    "source" "ComplianceIssueSource" NOT NULL DEFAULT 'INTERNAL_AUDIT',
    "reviewerNotes" TEXT,
    "remediation" TEXT,
    "resolution" TEXT,
    "appVersionId" TEXT,
    "platformId" TEXT,
    "countryId" TEXT,
    "requirementId" TEXT,
    "reportedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "resolvedAt" TIMESTAMP(3),
    "assigneeId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_issues_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_evidence" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'DOCUMENT',
    "url" TEXT NOT NULL,
    "description" TEXT,
    "requirementId" TEXT,
    "checklistItemId" TEXT,
    "issueId" TEXT,
    "uploadedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "compliance_evidence_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_release_overrides" (
    "id" TEXT NOT NULL,
    "reviewId" TEXT NOT NULL,
    "adminId" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "previousStatus" "ComplianceReviewStatus" NOT NULL,
    "newStatus" "ComplianceReviewStatus" NOT NULL,
    "overriddenIssues" TEXT NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "compliance_release_overrides_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_audit_logs" (
    "id" TEXT NOT NULL,
    "actorId" TEXT,
    "actorEmail" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "targetType" TEXT NOT NULL,
    "targetId" TEXT,
    "previousValue" TEXT,
    "newValue" TEXT,
    "platform" TEXT,
    "country" TEXT,
    "version" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "compliance_audit_logs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "compliance_legal_links" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "contentMarkdown" TEXT,
    "countryCode" TEXT,
    "platformCode" TEXT,
    "lastVerifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "compliance_legal_links_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_regions_code_key" ON "compliance_regions"("code");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_countries_code_key" ON "compliance_countries"("code");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_countries_regionId_idx" ON "compliance_countries"("regionId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_platforms_code_key" ON "compliance_platforms"("code");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_distributions_code_key" ON "compliance_distributions"("code");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_distributions_platformId_idx" ON "compliance_distributions"("platformId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_app_versions_platformId_status_idx" ON "compliance_app_versions"("platformId", "status");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_app_versions_platformId_version_key" ON "compliance_app_versions"("platformId", "version");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_policies_code_key" ON "compliance_policies"("code");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_requirements_code_key" ON "compliance_requirements"("code");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirements_category_severity_idx" ON "compliance_requirements"("category", "severity");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirements_policyId_idx" ON "compliance_requirements"("policyId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirement_scopes_requirementId_idx" ON "compliance_requirement_scopes"("requirementId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirement_scopes_countryId_idx" ON "compliance_requirement_scopes"("countryId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirement_scopes_regionId_idx" ON "compliance_requirement_scopes"("regionId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirement_scopes_platformId_idx" ON "compliance_requirement_scopes"("platformId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_requirement_scopes_distributionId_idx" ON "compliance_requirement_scopes"("distributionId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_reviews_appVersionId_idx" ON "compliance_reviews"("appVersionId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_reviews_platformId_status_idx" ON "compliance_reviews"("platformId", "status");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_checklist_items_reviewId_status_idx" ON "compliance_checklist_items"("reviewId", "status");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_checklist_items_reviewId_requirementId_key" ON "compliance_checklist_items"("reviewId", "requirementId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_issues_status_severity_idx" ON "compliance_issues"("status", "severity");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_issues_platformId_appVersionId_idx" ON "compliance_issues"("platformId", "appVersionId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_evidence_requirementId_idx" ON "compliance_evidence"("requirementId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_evidence_checklistItemId_idx" ON "compliance_evidence"("checklistItemId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_evidence_issueId_idx" ON "compliance_evidence"("issueId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_release_overrides_reviewId_idx" ON "compliance_release_overrides"("reviewId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_audit_logs_createdAt_idx" ON "compliance_audit_logs"("createdAt");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "compliance_audit_logs_targetType_targetId_idx" ON "compliance_audit_logs"("targetType", "targetId");

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "compliance_legal_links_key_countryCode_platformCode_key" ON "compliance_legal_links"("key", "countryCode", "platformCode");

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_countries_regionId_fkey'
  ) THEN
    ALTER TABLE "compliance_countries" ADD CONSTRAINT "compliance_countries_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "compliance_regions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_distributions_platformId_fkey'
  ) THEN
    ALTER TABLE "compliance_distributions" ADD CONSTRAINT "compliance_distributions_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "compliance_platforms"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_app_versions_platformId_fkey'
  ) THEN
    ALTER TABLE "compliance_app_versions" ADD CONSTRAINT "compliance_app_versions_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "compliance_platforms"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirements_policyId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirements" ADD CONSTRAINT "compliance_requirements_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "compliance_policies"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirement_scopes_requirementId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirement_scopes" ADD CONSTRAINT "compliance_requirement_scopes_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "compliance_requirements"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirement_scopes_countryId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirement_scopes" ADD CONSTRAINT "compliance_requirement_scopes_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "compliance_countries"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirement_scopes_regionId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirement_scopes" ADD CONSTRAINT "compliance_requirement_scopes_regionId_fkey" FOREIGN KEY ("regionId") REFERENCES "compliance_regions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirement_scopes_platformId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirement_scopes" ADD CONSTRAINT "compliance_requirement_scopes_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "compliance_platforms"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_requirement_scopes_distributionId_fkey'
  ) THEN
    ALTER TABLE "compliance_requirement_scopes" ADD CONSTRAINT "compliance_requirement_scopes_distributionId_fkey" FOREIGN KEY ("distributionId") REFERENCES "compliance_distributions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_reviews_appVersionId_fkey'
  ) THEN
    ALTER TABLE "compliance_reviews" ADD CONSTRAINT "compliance_reviews_appVersionId_fkey" FOREIGN KEY ("appVersionId") REFERENCES "compliance_app_versions"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_reviews_platformId_fkey'
  ) THEN
    ALTER TABLE "compliance_reviews" ADD CONSTRAINT "compliance_reviews_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "compliance_platforms"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_reviews_distributionId_fkey'
  ) THEN
    ALTER TABLE "compliance_reviews" ADD CONSTRAINT "compliance_reviews_distributionId_fkey" FOREIGN KEY ("distributionId") REFERENCES "compliance_distributions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_reviews_countryId_fkey'
  ) THEN
    ALTER TABLE "compliance_reviews" ADD CONSTRAINT "compliance_reviews_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "compliance_countries"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_reviews_reviewerId_fkey'
  ) THEN
    ALTER TABLE "compliance_reviews" ADD CONSTRAINT "compliance_reviews_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_checklist_items_reviewId_fkey'
  ) THEN
    ALTER TABLE "compliance_checklist_items" ADD CONSTRAINT "compliance_checklist_items_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "compliance_reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_checklist_items_requirementId_fkey'
  ) THEN
    ALTER TABLE "compliance_checklist_items" ADD CONSTRAINT "compliance_checklist_items_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "compliance_requirements"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_checklist_items_assignedToId_fkey'
  ) THEN
    ALTER TABLE "compliance_checklist_items" ADD CONSTRAINT "compliance_checklist_items_assignedToId_fkey" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_checklist_items_verifiedById_fkey'
  ) THEN
    ALTER TABLE "compliance_checklist_items" ADD CONSTRAINT "compliance_checklist_items_verifiedById_fkey" FOREIGN KEY ("verifiedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_issues_appVersionId_fkey'
  ) THEN
    ALTER TABLE "compliance_issues" ADD CONSTRAINT "compliance_issues_appVersionId_fkey" FOREIGN KEY ("appVersionId") REFERENCES "compliance_app_versions"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_issues_platformId_fkey'
  ) THEN
    ALTER TABLE "compliance_issues" ADD CONSTRAINT "compliance_issues_platformId_fkey" FOREIGN KEY ("platformId") REFERENCES "compliance_platforms"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_issues_countryId_fkey'
  ) THEN
    ALTER TABLE "compliance_issues" ADD CONSTRAINT "compliance_issues_countryId_fkey" FOREIGN KEY ("countryId") REFERENCES "compliance_countries"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_issues_requirementId_fkey'
  ) THEN
    ALTER TABLE "compliance_issues" ADD CONSTRAINT "compliance_issues_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "compliance_requirements"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_issues_assigneeId_fkey'
  ) THEN
    ALTER TABLE "compliance_issues" ADD CONSTRAINT "compliance_issues_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_evidence_requirementId_fkey'
  ) THEN
    ALTER TABLE "compliance_evidence" ADD CONSTRAINT "compliance_evidence_requirementId_fkey" FOREIGN KEY ("requirementId") REFERENCES "compliance_requirements"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_evidence_checklistItemId_fkey'
  ) THEN
    ALTER TABLE "compliance_evidence" ADD CONSTRAINT "compliance_evidence_checklistItemId_fkey" FOREIGN KEY ("checklistItemId") REFERENCES "compliance_checklist_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_evidence_issueId_fkey'
  ) THEN
    ALTER TABLE "compliance_evidence" ADD CONSTRAINT "compliance_evidence_issueId_fkey" FOREIGN KEY ("issueId") REFERENCES "compliance_issues"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_evidence_uploadedById_fkey'
  ) THEN
    ALTER TABLE "compliance_evidence" ADD CONSTRAINT "compliance_evidence_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_release_overrides_reviewId_fkey'
  ) THEN
    ALTER TABLE "compliance_release_overrides" ADD CONSTRAINT "compliance_release_overrides_reviewId_fkey" FOREIGN KEY ("reviewId") REFERENCES "compliance_reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_release_overrides_adminId_fkey'
  ) THEN
    ALTER TABLE "compliance_release_overrides" ADD CONSTRAINT "compliance_release_overrides_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_legal_links_countryCode_fkey'
  ) THEN
    ALTER TABLE "compliance_legal_links" ADD CONSTRAINT "compliance_legal_links_countryCode_fkey" FOREIGN KEY ("countryCode") REFERENCES "compliance_countries"("code") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- AddForeignKey
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'compliance_legal_links_platformCode_fkey'
  ) THEN
    ALTER TABLE "compliance_legal_links" ADD CONSTRAINT "compliance_legal_links_platformCode_fkey" FOREIGN KEY ("platformCode") REFERENCES "compliance_platforms"("code") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;

-- RenameIndex
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'app_releases_platform_operatingSystem_releaseChannel_version_ke') THEN
    ALTER INDEX "app_releases_platform_operatingSystem_releaseChannel_version_ke" RENAME TO "app_releases_platform_operatingSystem_releaseChannel_versio_key";
  END IF;
END $$;

-- RenameIndex
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_class WHERE relname = 'cross_object_links_workspaceId_sourceType_sourceId_targetType_t') THEN
    ALTER INDEX "cross_object_links_workspaceId_sourceType_sourceId_targetType_t" RENAME TO "cross_object_links_workspaceId_sourceType_sourceId_targetTy_key";
  END IF;
END $$;

