export { PrismaService } from './lib/prisma.service.js';
export { PrismaModule } from './lib/prisma.module.js';

/**
 * Re-export the generated client so feature libraries import model types from
 * `@org/database` rather than reaching into a generated folder by path.
 */
export {
  Prisma,
  PrismaClient,
  ChannelRole,
  ChannelVisibility,
  InvitationStatus,
  MembershipStatus,
  PresenceStatus,
  SystemRole,
  WorkspaceRole,
  WorkspaceStatus,
  TaskStatus,
  TaskPriority,
  ProjectStatus,
  DocumentKind,
  IdentifierPrefixMode,
  ProjectHealth,
  WorkItemType,
  RelationType,
  CycleStatus,
  CustomFieldType,
  ViewType,
  IntakeStatus,
  IntakeSource,
  ActivityKind,
  NotificationKind,
  MeetingStatus,
  MeetingParticipantRole,
  MeetingRsvp,
} from './generated/client.js';

export type {
  Channel,
  ChannelMember,
  ChannelPin,
  Invitation,
  PasswordResetToken,
  RefreshToken,
  Upload,
  User,
  Workspace,
  WorkspaceMember,
  Team,
  Initiative,
  Project,
  Epic,
  Module,
  Cycle,
  Milestone,
  Sprint,
  Task,
  TaskComment,
  WorkItemRelation,
  WorkItemCustomField,
  SavedView,
  IntakeRequest,
  ProjectUpdate,
  WorkItemActivity,
  CalendarEvent,
  Meeting,
  MeetingParticipant,
  MeetingNote,
  MeetingDecision,
  WorkDocument,
  Whiteboard,
  PromptTemplate,
  AIMemory,
  AIChatSession,
  AIAgent,
  AgentSchedule,
  AgentExecutionLog,
  AutomationWorkflow,
  WorkflowExecution,
  Organization,
  Department,
  SSOConfig,
  EnterpriseAuditLog,
  OrganizationSubscription,
  ExternalIntegration,
  IntegrationWebhookEvent,
  IntegrationSyncJob,
  IntegrationAuditLog,
  ImportJob,
  AnalyticsEvent,
  RecentActivity,
  Notification,
} from './generated/client.js';
