import type { PublishListingInput } from './marketplace.types.js';

export const SEED_PUBLISHER = {
  slug: 'onetab-official',
  name: 'OneTab Ecosystem',
  isVerified: true,
  websiteUrl: 'https://onetab.ai',
  supportEmail: 'integrations@onetab.ai',
};

export const SEED_LISTINGS: PublishListingInput[] = [
  // ==========================================
  // APPS (Integrations & Productivity Tools)
  // ==========================================
  {
    kind: 'INTEGRATION',
    slug: 'github',
    name: 'GitHub',
    tagline: 'Pull request reviews, issue tracking, and CI/CD workflow automation',
    description: `Connect your GitHub repositories to OneTab AI for seamless developer workflows. Receive real-time pull request notifications, mention issues directly in discussions with automated previews, monitor build statuses, and trigger automated code reviews right inside your channels.

### Key Workflows
- **Pull Request Notifications**: Instant alerts when PRs are opened, approved, merged, or request your review.
- **Issue Expansion**: Type '#issue-id' or '/github issue' to generate rich interactive cards with labels, assignees, and milestone status.
- **CI/CD Build Alerts**: Catch failing tests before merging with direct links to workflow runs.`,
    category: 'Developer Tools',
    version: '2.4.0',
    iconUrl: 'https://cdn.simpleicons.org/github/181717',
    previewUrl: 'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
    tags: ['github', 'git', 'pull-requests', 'ci-cd', 'developer'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'GitHub / OneTab Verified',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Bi-directional GitHub Issue sync',
        'Pull request review requests & merge alerts',
        'Workflow & GitHub Actions run monitors',
        'Direct commit and branch linking',
      ],
      permissions: [
        {
          scope: 'read:channels',
          name: 'Read channels',
          level: 'READ',
          description: 'Monitor channels where GitHub notifications are enabled',
        },
        {
          scope: 'write:messages',
          name: 'Send messages',
          level: 'WRITE',
          description: 'Post PR notifications and issue status cards',
        },
        {
          scope: 'read:workspace',
          name: 'Read workspace profile',
          level: 'READ',
          description: 'Match GitHub usernames to OneTab workspace members',
        },
        {
          scope: 'net:fetch',
          name: 'External API access',
          level: 'SENSITIVE',
          description: 'Communicate securely with api.github.com',
        },
      ],
      commands: [
        {
          command: '/github issue',
          description: 'Search or create a GitHub issue',
          args: '<search or title>',
        },
        {
          command: '/github pr',
          description: 'Inspect status and approvals of a pull request',
          args: '<pr-number>',
        },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Repository names', 'Issue titles & descriptions', 'PR diff summaries'],
        authentication: 'OAuth 2.0 Webhook Integration',
        dataStorage: 'Encrypted tokens at rest (AES-256-GCM)',
        externalServices: ['https://api.github.com'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: {
        minVersion: '1.0.0',
        platforms: ['Web', 'Desktop', 'Mobile'],
      },
      screenshots: [
        'https://images.unsplash.com/photo-1618401471353-b98aedd04e11?w=800&auto=format&fit=crop&q=80',
      ],
      changelog: [
        { version: '2.4.0', date: '2026-08-20', notes: 'Added GitHub Actions CI/CD failure summaries' },
        { version: '2.3.1', date: '2026-06-12', notes: 'Optimized webhook delivery speed' },
      ],
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'linear',
    name: 'Linear',
    tagline: 'Streamlined issue tracking, cycle progress, and workspace ticket linking',
    description: `Connect Linear to bring issue management, project roadmaps, and cycle tracking directly into your conversations. Create Linear issues from chat messages with a single click, automatically link discussions to tickets, and track cycle burn-down without leaving OneTab.`,
    category: 'Project Management',
    version: '1.8.0',
    iconUrl: 'https://cdn.simpleicons.org/linear/5E6AD2',
    previewUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=800&auto=format&fit=crop&q=80',
    tags: ['linear', 'issues', 'project-management', 'cycles', 'agile'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Linear / Verified Partner',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Create Linear issues from message actions',
        'Automatic issue unfurling with status and priority badges',
        'Sprint cycle progress updates',
        'Two-way issue status synchronization',
      ],
      permissions: [
        {
          scope: 'read:channels',
          name: 'Read channel messages',
          level: 'READ',
          description: 'Detect Linear issue identifiers (e.g. ENG-123)',
        },
        {
          scope: 'write:messages',
          name: 'Post issue previews',
          level: 'WRITE',
          description: 'Render interactive issue cards and action buttons',
        },
        {
          scope: 'write:tasks',
          name: 'Sync workspace tasks',
          level: 'WRITE',
          description: 'Synchronize Kanban tasks with Linear backlog',
        },
        {
          scope: 'net:fetch',
          name: 'Linear GraphQL API',
          level: 'SENSITIVE',
          description: 'Communicate with api.linear.app',
        },
      ],
      commands: [
        {
          command: '/linear issue',
          description: 'Create or look up a Linear ticket',
          args: '<title or identifier>',
        },
        {
          command: '/linear cycle',
          description: 'View current active cycle burn-down and blockers',
        },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Linear teams', 'Issue titles & states', 'Assignee names'],
        authentication: 'OAuth 2.0 with PKCE',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://api.linear.app'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
      changelog: [
        { version: '1.8.0', date: '2026-07-15', notes: 'Support for initiative and project milestone linking' },
      ],
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'slack',
    name: 'Slack Connector',
    tagline: 'Real-time bidirectional channel bridging and external team messaging',
    description: `Bridge specific OneTab channels to Slack workspaces. Enable partner teams, clients, and external contractors using Slack to collaborate transparently with your OneTab AI workspace in real-time with full rich-text, attachments, and thread support.`,
    category: 'Communication',
    version: '2.1.0',
    iconUrl: 'https://cdn.simpleicons.org/slack/4A154B',
    tags: ['slack', 'bridge', 'chat', 'messaging', 'communication'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab Integrations',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Bi-directional cross-platform channel mirroring',
        'Thread reply mapping between OneTab and Slack',
        'Avatar and display name preservation',
        'File attachment synchronization',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read linked channels', level: 'READ', description: 'Monitor messages in bridged channels' },
        { scope: 'write:messages', name: 'Post bridged messages', level: 'WRITE', description: 'Forward messages from Slack into OneTab' },
        { scope: 'write:files', name: 'Sync attachments', level: 'WRITE', description: 'Store uploaded images and documents' },
      ],
      commands: [
        { command: '/slack bridge', description: 'Link current channel to a Slack channel', args: '#channel-name' },
        { command: '/slack status', description: 'Check sync health and latency of Slack bridge' },
      ],
      requiresAdmin: true,
      security: {
        dataAccessed: ['Messages in bridged channels only', 'Author display names'],
        authentication: 'Slack Bot User OAuth Token',
        dataStorage: 'In-memory message ID routing table',
        externalServices: ['https://slack.com/api'],
        dataBoundaries: 'Scoped strictly to bridged channels',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'notion',
    name: 'Notion Knowledge',
    tagline: 'Unified doc search, page importing, and collaborative wiki synchronization',
    description: `Connect Notion to empower your workspace with shared company knowledge. Search Notion databases directly from chat, convert discussions into structured Notion documentation, and keep team guidelines aligned across systems.`,
    category: 'Productivity',
    version: '1.5.0',
    iconUrl: 'https://cdn.simpleicons.org/notion/000000',
    tags: ['notion', 'docs', 'wiki', 'knowledge', 'notes'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Notion / Verified Partner',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Search Notion pages and databases in real-time',
        'Export channel decisions to Notion wikis',
        'Preview Notion links with author and last edited metadata',
      ],
      permissions: [
        { scope: 'read:documents', name: 'Read documents', level: 'READ', description: 'Query internal docs for knowledge retrieval' },
        { scope: 'write:documents', name: 'Create docs', level: 'WRITE', description: 'Draft meeting summaries and wikis' },
        { scope: 'net:fetch', name: 'Notion API', level: 'SENSITIVE', description: 'Communicate with api.notion.com' },
      ],
      commands: [
        { command: '/notion search', description: 'Find pages in Notion', args: '<search query>' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Notion page titles, properties, and blocks'],
        authentication: 'OAuth 2.0 Internal Integration Token',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://api.notion.com'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'google-calendar',
    name: 'Google Calendar & Meet',
    tagline: 'Schedule meetings, view daily agendas, and receive huddle reminders',
    description: `Integrate Google Calendar to streamline team scheduling. View upcoming events, schedule huddles with automated Google Meet links, and receive timely notifications before important discussions begin.`,
    category: 'Productivity',
    version: '2.0.1',
    iconUrl: 'https://cdn.simpleicons.org/googlecalendar/4285F4',
    tags: ['google', 'calendar', 'meetings', 'meet', 'schedule'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Google Workspace',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Daily agenda overview directly in Inbox and Chat',
        'One-click meeting scheduling with auto-generated Meet links',
        'Smart huddle reminders 5 minutes before scheduled calls',
      ],
      permissions: [
        { scope: 'read:members', name: 'Read member emails', level: 'READ', description: 'Identify participant calendars' },
        { scope: 'write:messages', name: 'Post reminders', level: 'WRITE', description: 'Send agenda alerts' },
      ],
      commands: [
        { command: '/gcal today', description: 'View your agenda for today' },
        { command: '/gcal meet', description: 'Create a meeting with Google Meet link', args: '[title] [time]' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Calendar event times, titles, and participant emails'],
        authentication: 'Google OAuth 2.0 with Calendar Scopes',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://www.googleapis.com'],
        dataBoundaries: 'User-authorized calendar access',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'google-drive',
    name: 'Google Drive & Docs',
    tagline: 'Unified cloud file search, document creation, and sheet previews',
    description: `Access files from Google Drive without leaving OneTab AI. Search across documents, sheets, and presentations, embed file cards with live thumbnail previews, and grant channel members granular view permissions effortlessly.`,
    category: 'Productivity',
    version: '1.9.0',
    iconUrl: 'https://cdn.simpleicons.org/googledrive/4285F4',
    tags: ['google', 'drive', 'docs', 'sheets', 'files', 'storage'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Google Workspace',
    manifest: {
      entityType: 'APP',
      badge: 'OFFICIAL',
      capabilities: [
        'Search files across your Google Drive from global search and composer',
        'Inline previews of Docs, Sheets, and Slides attachments',
        'Automatic permission prompting for channel members',
      ],
      permissions: [
        { scope: 'read:files', name: 'Read files', level: 'READ', description: 'Access Drive search results' },
        { scope: 'write:files', name: 'Attach files', level: 'WRITE', description: 'Link Drive assets to messages' },
      ],
      commands: [
        { command: '/gdrive search', description: 'Search files across Google Drive', args: '<query>' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['File names, URLs, thumbnails, and MIME types'],
        authentication: 'Google OAuth 2.0',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://www.googleapis.com'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'jira',
    name: 'Jira Software',
    tagline: 'Enterprise sprint tracking, issue transitions, and backlog alignment',
    description: `Connect Atlassian Jira Software to manage enterprise engineering projects. Preview Jira tickets, transition issue states, and track sprint deliverables directly within your workflow channels.`,
    category: 'Project Management',
    version: '2.2.0',
    iconUrl: 'https://cdn.simpleicons.org/jira/0052CC',
    tags: ['jira', 'atlassian', 'enterprise', 'sprint', 'scrum', 'backlog'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Atlassian Verified',
    manifest: {
      entityType: 'APP',
      badge: 'VERIFIED',
      capabilities: [
        'Automatic Jira key expansion (e.g. PROJ-456)',
        'Issue transition buttons inside message cards',
        'Sprint status reporting and velocity charts',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read channel text', level: 'READ', description: 'Detect Jira ticket identifiers' },
        { scope: 'write:messages', name: 'Render Jira cards', level: 'WRITE', description: 'Display rich issue widgets' },
        { scope: 'net:fetch', name: 'Atlassian Cloud API', level: 'SENSITIVE', description: 'Connect to Atlassian endpoints' },
      ],
      commands: [
        { command: '/jira ticket', description: 'Inspect or transition a Jira issue', args: '<issue-key>' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Jira issue keys, summaries, status names'],
        authentication: 'Atlassian Connect OAuth 2.0 (3LO)',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://api.atlassian.com'],
        dataBoundaries: 'Tenant scoped',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'figma',
    name: 'Figma',
    tagline: 'Live design canvas previews, frame embeds, and comment sync',
    description: `Bring your product design workflow into OneTab AI. Paste Figma links to render interactive design previews, receive notifications when someone comments on your frames, and share feedback without leaving chat.`,
    category: 'Developer Tools',
    version: '1.4.2',
    iconUrl: 'https://cdn.simpleicons.org/figma/F24E1E',
    tags: ['figma', 'design', 'ui', 'ux', 'prototypes', 'frames'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Figma Verified',
    manifest: {
      entityType: 'APP',
      badge: 'VERIFIED',
      capabilities: [
        'Live Figma frame embeds and vector asset previews',
        'Real-time design comment and mention notifications',
        'Design version diff tracking',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read links', level: 'READ', description: 'Unfurl figma.com URLs' },
        { scope: 'write:messages', name: 'Post previews', level: 'WRITE', description: 'Render image previews and comments' },
      ],
      commands: [
        { command: '/figma preview', description: 'Embed a Figma frame or component', args: '<figma-url>' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Figma file IDs, frame images, comment texts'],
        authentication: 'OAuth 2.0 Webhook',
        dataStorage: 'Cached frame preview metadata',
        externalServices: ['https://api.figma.com'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'trello',
    name: 'Trello Boards',
    tagline: 'Lightweight Kanban card tracking, checklist sync, and board updates',
    description: `Connect Trello boards to track tasks, organize ideas, and update project checklists effortlessly. Move cards between lists, add checklist items, and assign teammates from chat discussions.`,
    category: 'Productivity',
    version: '1.3.0',
    iconUrl: 'https://cdn.simpleicons.org/trello/0052CC',
    tags: ['trello', 'kanban', 'cards', 'boards', 'tasks'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Atlassian Verified',
    manifest: {
      entityType: 'APP',
      badge: 'VERIFIED',
      capabilities: [
        'Card creation from message context menu',
        'List move notifications and milestone alerts',
        'Two-way sync with OneTab Kanban boards',
      ],
      permissions: [
        { scope: 'read:tasks', name: 'Read tasks', level: 'READ', description: 'Read local tasks for sync' },
        { scope: 'write:tasks', name: 'Write tasks', level: 'WRITE', description: 'Create and update tasks' },
      ],
      commands: [
        { command: '/trello card', description: 'Create card on a specified board', args: '[board] [title]' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Card titles, descriptions, and list names'],
        authentication: 'Trello API Key & Token',
        dataStorage: 'Encrypted credentials at rest',
        externalServices: ['https://api.trello.com'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'zendesk',
    name: 'Zendesk Support',
    tagline: 'Customer support ticket escalation, SLA tracking, and resolution alerts',
    description: `Bridge customer support and product engineering. Escalate urgent Zendesk tickets into engineering channels, alert on-call teams of SLA breaches, and draft verified customer responses cooperatively.`,
    category: 'Customer Support & Communication',
    version: '1.6.1',
    iconUrl: 'https://cdn.simpleicons.org/zendesk/03363D',
    tags: ['zendesk', 'support', 'helpdesk', 'tickets', 'customers'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'Zendesk Verified',
    manifest: {
      entityType: 'APP',
      badge: 'VERIFIED',
      capabilities: [
        'Real-time high-priority ticket escalation alerts',
        'Ticket status updating from channel message actions',
        'Customer sentiment indicators and CSAT tracking',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read support channels', level: 'READ', description: 'Monitor customer support escalation feeds' },
        { scope: 'write:messages', name: 'Post ticket alerts', level: 'WRITE', description: 'Deliver ticket widgets' },
        { scope: 'net:fetch', name: 'Zendesk REST API', level: 'SENSITIVE', description: 'Connect to zendesk.com' },
      ],
      commands: [
        { command: '/zendesk ticket', description: 'Lookup ticket details and conversation thread', args: '<ticket-id>' },
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Ticket subject, description, priority, customer name'],
        authentication: 'OAuth 2.0 Webhook Subscriptions',
        dataStorage: 'Encrypted tokens at rest',
        externalServices: ['https://zendesk.com/api'],
        dataBoundaries: 'Tenant isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'custom-webhooks',
    name: 'Custom Webhook Engine',
    tagline: 'Inbound and outbound JSON webhooks, event triggers, and REST dispatch',
    description: `Build custom internal integrations and connect homegrown services. Configure authenticated inbound webhooks with customizable JSON payload templates, or dispatch signed outbound webhooks when workspace events occur.`,
    category: 'Automation',
    version: '3.0.0',
    iconUrl: 'https://cdn.simpleicons.org/webhooks/000000',
    tags: ['webhooks', 'automation', 'api', 'custom', 'internal', 'developer'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab Core',
    manifest: {
      entityType: 'APP',
      badge: 'INTERNAL',
      capabilities: [
        'Configurable incoming webhook endpoints with HMAC-SHA256 signature verification',
        'Custom payload JSON transformation and markdown templating',
        'Outbound event webhooks with automatic retries and dead-letter queues',
      ],
      permissions: [
        { scope: 'read:workspace', name: 'Read workspace metadata', level: 'READ', description: 'Verify workspace routing' },
        { scope: 'write:messages', name: 'Dispatch messages', level: 'WRITE', description: 'Post payload messages to selected channels' },
        { scope: 'write:workspace', name: 'Admin webhook endpoints', level: 'ADMIN', description: 'Manage webhook secret keys' },
        { scope: 'net:fetch', name: 'Egress webhooks', level: 'SENSITIVE', description: 'Dispatch HTTP POST to configured endpoints' },
      ],
      commands: [
        { command: '/webhook test', description: 'Trigger test webhook dispatch', args: '<webhook-id>' },
      ],
      requiresAdmin: true,
      security: {
        dataAccessed: ['Configured payload bodies only'],
        authentication: 'HMAC-SHA256 Secret Signing',
        dataStorage: 'Encrypted endpoint URLs and signing secrets',
        externalServices: ['User-configured webhook destinations'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'INTEGRATION',
    slug: 'analytics-pulse',
    name: 'Analytics Pulse',
    tagline: 'Workspace health telemetry, member active trends, and export metrics',
    description: `Track workspace adoption and productivity signals. Gain privacy-preserving insights into channel message volume, active collaboration periods, response latency, and task completion velocity across your organization.`,
    category: 'Workspace Utilities',
    version: '1.2.0',
    iconUrl: 'https://cdn.simpleicons.org/datadog/632CA6',
    tags: ['analytics', 'metrics', 'insights', 'health', 'utilities'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab Core',
    manifest: {
      entityType: 'APP',
      badge: 'INTERNAL',
      capabilities: [
        'Weekly workspace activity summary delivered to #general or admin channels',
        'Task completion rate and cycle time metrics',
        'CSV/JSON export of aggregated collaboration statistics',
      ],
      permissions: [
        { scope: 'read:analytics', name: 'Read analytics telemetry', level: 'READ', description: 'Aggregate workspace message & task counts' },
        { scope: 'write:messages', name: 'Post weekly digest', level: 'WRITE', description: 'Share summary graphs in designated channels' },
      ],
      commands: [
        { command: '/analytics weekly', description: 'Generate immediate weekly productivity pulse summary' },
      ],
      requiresAdmin: true,
      security: {
        dataAccessed: ['Aggregated activity counters (anonymized, no message body inspection)'],
        authentication: 'Internal Service Role',
        dataStorage: 'Timeseries rollups in local database',
        externalServices: [],
        dataBoundaries: 'Never leaves workspace boundary',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },

  // ==========================================
  // AGENTS (Autonomous & Intelligent Agents)
  // ==========================================
  {
    kind: 'AGENT',
    slug: 'code-reviewer',
    name: 'Code Reviewer & Security Sentinel',
    tagline: 'Autonomous engineering assistant that inspects pull requests, security flaws, and test coverage',
    description: `An intelligent autonomous agent designed for engineering teams. Code Reviewer automatically inspects code diffs, detects OWASP security vulnerabilities and hardcoded credentials, evaluates TypeScript typing soundness, and suggests optimized unit tests before code merges.

### Capabilities & Role
- **Pull Request Inspection**: Automated assessment of pull requests with inline suggestions.
- **Security Scanner**: Detects exposed secrets, SQL injections, insecure deserialization, and cross-site scripting risks.
- **Test Coverage Assistance**: Generates idiomatic Vitest, Jest, or Playwright test specifications from code snippets.
- **Clear Boundaries**: Never commits code or merges branches without explicit human approval.`,
    category: 'Engineering',
    version: '2.0.0',
    iconUrl: 'icon:code',
    previewUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&auto=format&fit=crop&q=80',
    tags: ['code-review', 'security', 'engineering', 'typescript', 'ai-agent', 'testing'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Automated pull request diff analysis',
        'Security vulnerability & secrets detection',
        'Unit and integration test specification generation',
        'Architecture consistency recommendations',
      ],
      permissions: [
        {
          scope: 'read:channels',
          name: 'Read channel discussions',
          level: 'READ',
          description: 'Understand engineering discussion context in linked channels',
        },
        {
          scope: 'write:messages',
          name: 'Post code reviews',
          level: 'WRITE',
          description: 'Share structured review findings and inline comments',
        },
        {
          scope: 'read:tasks',
          name: 'Read tasks',
          level: 'READ',
          description: 'Link issues to pull requests',
        },
        {
          scope: 'ai:invoke',
          name: 'LLM inference',
          level: 'READ',
          description: 'Execute deep code analysis using local or cloud AI models',
        },
      ],
      commands: [
        {
          command: '/agent review',
          description: 'Trigger automated code review on a file or PR link',
          args: '<pr-url or code block>',
        },
        {
          command: '/agent scan-security',
          description: 'Run static security vulnerability assessment on recent changes',
        },
      ],
      examplePrompts: [
        'Review recent PR changes for potential race conditions',
        'Scan workspace code for hardcoded secrets or API tokens',
        'Draft a Vitest unit test suite for the auth controller',
        'Explain how to refactor this complex reducer function',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Code snippets, Git diffs, Channel discussion context'],
        authentication: 'Isolated Agent Worker Environment',
        dataStorage: 'Ephemerally processed in session memory',
        externalServices: ['Configured AI Provider (NVIDIA Nemotron / Llama 3)'],
        dataBoundaries: 'Workspace boundary enforced. No training on user code.',
        modelProvider: 'Nemotron-3-Super / Llama 3.3',
        approvalRequiredActions: ['Merging pull requests', 'Deploying code to production'],
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
      changelog: [
        { version: '2.0.0', date: '2026-08-10', notes: 'Integrated multi-file contextual AST analysis' },
        { version: '1.5.0', date: '2026-05-18', notes: 'Added OWASP Top 10 automated ruleset' },
      ],
    },
  },
  {
    kind: 'AGENT',
    slug: 'support-triage',
    name: 'Support Triage & Customer Copilot',
    tagline: 'Auto-categorize customer inquiries, route issues, and draft empathetic verified replies',
    description: `Empower your customer support and success teams with an intelligent triage agent. Support Triage reads incoming inquiries, detects customer urgency and sentiment, checks your documentation for verified solutions, and drafts high-quality response recommendations for agent review.`,
    category: 'Customer Support & Communication',
    version: '1.9.0',
    iconUrl: 'icon:chat',
    tags: ['support', 'customer-service', 'triage', 'sentiment', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Customer sentiment analysis and churn risk scoring',
        'Automated ticket categorization and tier assignment',
        'Knowledge-base grounded response drafting',
        'Multi-lingual inquiry translation and formatting',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read support channels', level: 'READ', description: 'Monitor customer inquiry channels' },
        { scope: 'write:messages', name: 'Post drafted replies', level: 'WRITE', description: 'Suggest responses to human agents' },
        { scope: 'read:documents', name: 'Read company knowledge', level: 'READ', description: 'Verify facts in company wiki' },
        { scope: 'ai:invoke', name: 'AI reasoning engine', level: 'READ', description: 'Classify tone and draft messages' },
      ],
      commands: [
        { command: '/agent triage', description: 'Triage pending customer issue in thread' },
        { command: '/agent draft-reply', description: 'Draft customer response with tone controls', args: '[empathetic | technical]' },
      ],
      examplePrompts: [
        'Summarize the customer complaint in this thread',
        'Draft an empathetic reply explaining our refund policy',
        'Categorize the 5 most frequent support questions this week',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Customer tickets, product documentation'],
        authentication: 'Sandboxed LLM Agent',
        dataStorage: 'Ephemeral session context',
        externalServices: ['Local or Cloud AI Provider'],
        dataBoundaries: 'Never shares PII externally',
        approvalRequiredActions: ['Sending message directly to customer without agent review'],
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'meeting-synthesizer',
    name: 'Meeting Synthesizer & Note Taker',
    tagline: 'Extracts key decisions, action items, and task follow-ups from huddles and recorded meetings',
    description: `Never lose track of meeting decisions or action items again. Meeting Synthesizer joins or analyzes audio transcripts from huddles and recorded meetings, formats clear bullet-point takeaways, highlights agreed-upon decisions, and turns commitments into assigned OneTab tasks.`,
    category: 'Productivity',
    version: '1.7.0',
    iconUrl: 'icon:spark',
    tags: ['meetings', 'huddles', 'notes', 'action-items', 'summary', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Live and post-call speech-to-text transcript synthesis',
        'Action item extraction with automatic assignee tagging',
        'Key architectural decision record (ADR) drafting',
        'Exporting meeting notes to collaborative OneTab docs',
      ],
      permissions: [
        { scope: 'read:messages', name: 'Read transcript text', level: 'READ', description: 'Process conversation flow' },
        { scope: 'write:tasks', name: 'Create follow-up tasks', level: 'WRITE', description: 'Turn action items into Kanban tasks' },
        { scope: 'write:documents', name: 'Create meeting notes', level: 'WRITE', description: 'Generate persistent meeting documentation' },
        { scope: 'ai:invoke', name: 'Speech & Text AI', level: 'READ', description: 'Extract entities and summaries' },
      ],
      commands: [
        { command: '/agent summarize-meeting', description: 'Generate recap of recent huddle or meeting transcript' },
      ],
      examplePrompts: [
        'Summarize today product sync meeting and highlight blockers',
        'Extract all action items from this huddle and assign to team members',
        'Draft an email update for executives based on this discussion',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Meeting transcripts and notes'],
        authentication: 'Internal Agent Worker',
        dataStorage: 'Saved as standard workspace documents',
        externalServices: ['Whisper & LLM Provider'],
        dataBoundaries: 'Workspace boundary strictly maintained',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'release-manager',
    name: 'Release Manager & Changelog Bot',
    tagline: 'Compiles changelogs, monitors semantic versions, and notifies channels on deployment',
    description: `Automate your software delivery communication. Release Manager tracks merged PRs across connected repositories, groups changes by feature, fix, or breaking change, drafts semantic release notes, and keeps stakeholder channels informed during deployments.`,
    category: 'Engineering',
    version: '1.4.0',
    iconUrl: 'icon:rocket',
    tags: ['releases', 'changelog', 'deployment', 'git', 'engineering', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Automatic semantic changelog generation from git commits and PR descriptions',
        'Breaking changes warning banner',
        'Deployment status broadcasts to designated announce channels',
      ],
      permissions: [
        { scope: 'read:channels', name: 'Read engineering channels', level: 'READ', description: 'Find release discussions' },
        { scope: 'write:messages', name: 'Post release notes', level: 'WRITE', description: 'Publish changelog announcements' },
        { scope: 'write:documents', name: 'Save release archives', level: 'WRITE', description: 'Maintain version history doc' },
      ],
      commands: [
        { command: '/agent draft-release', description: 'Draft release notes for a version tag', args: '<version>' },
      ],
      examplePrompts: [
        'Draft release notes for v2.5.0 based on PRs merged this sprint',
        'Check deployment status across staging and production environments',
        'List all breaking changes introduced in the last 14 days',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Git commit messages, PR titles, release tags'],
        authentication: 'Agent Worker',
        dataStorage: 'Ephemeral context',
        externalServices: ['Local AI Model'],
        dataBoundaries: 'Workspace isolated',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'knowledge-copilot',
    name: 'Knowledge Base & Docs Copilot',
    tagline: 'Semantic workspace wiki search, markdown page authoring, and automated FAQ generator',
    description: `Transform scattered workspace conversations and documents into structured organizational intelligence. Knowledge Copilot answers employee questions with exact citations, synthesizes long discussions into wikis, and flags outdated documentation for revision.`,
    category: 'Productivity',
    version: '2.1.0',
    iconUrl: 'icon:brain',
    tags: ['knowledge', 'docs', 'wiki', 'search', 'citations', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Semantic Q&A grounded in workspace documents and channel archives',
        'Citations linking directly to original source documents and timestamps',
        'Automated FAQ extraction from repetitive channel questions',
      ],
      permissions: [
        { scope: 'read:documents', name: 'Read all workspace docs', level: 'READ', description: 'Index documents for semantic retrieval' },
        { scope: 'read:channels', name: 'Read public channel archives', level: 'READ', description: 'Index answers and discussion conclusions' },
        { scope: 'write:documents', name: 'Author documentation', level: 'WRITE', description: 'Draft new pages and wiki updates' },
        { scope: 'ai:invoke', name: 'Embedding & LLM access', level: 'READ', description: 'Vector embeddings and RAG' },
      ],
      commands: [
        { command: '/agent ask', description: 'Ask questions with verified citations', args: '<question>' },
        { command: '/agent create-faq', description: 'Generate FAQ from current channel topic' },
      ],
      examplePrompts: [
        'Find our official policy on remote equipment reimbursement',
        'Generate an onboarding FAQ for new frontend engineers',
        'Summarize the architecture decisions made regarding offline sync',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Public channel messages and workspace documents'],
        authentication: 'RAG Vector Pipeline (Qdrant)',
        dataStorage: 'Vector embeddings with tenant encryption keys',
        externalServices: ['Embedding & LLM Model'],
        dataBoundaries: 'Never accesses private channels without explicit membership',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'sprint-planner',
    name: 'Task & Sprint Planner Agent',
    tagline: 'Backlog grooming assistant that assesses task dependencies, blockers, and cycle workload',
    description: `Optimize agile execution with an intelligent sprint copilot. Task & Sprint Planner analyzes team capacity, highlights dependency bottlenecks before sprints begin, recommends realistic sprint velocity targets, and breaks down complex features into actionable checklists.`,
    category: 'Project Management',
    version: '1.5.0',
    iconUrl: 'icon:layers',
    tags: ['sprint', 'planning', 'tasks', 'kanban', 'workload', 'agile', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Task dependency graph construction and critical path identification',
        'Workload balancing recommendations across team members',
        'Automated subtask decomposition from user story descriptions',
      ],
      permissions: [
        { scope: 'read:tasks', name: 'Read tasks and sprints', level: 'READ', description: 'Analyze backlog items' },
        { scope: 'write:tasks', name: 'Create and update tasks', level: 'WRITE', description: 'Adjust task estimates and relationships' },
        { scope: 'read:members', name: 'Read team capacity', level: 'READ', description: 'Evaluate workload distribution' },
      ],
      commands: [
        { command: '/agent plan-sprint', description: 'Analyze next sprint backlog for capacity and risks' },
        { command: '/agent breakdown', description: 'Break down a complex task into subtasks', args: '<task-id>' },
      ],
      examplePrompts: [
        'Analyze our upcoming sprint for unassigned dependencies',
        'Break down the "Mobile push notification architecture" feature into subtasks',
        'Identify overloaded team members in the current cycle',
      ],
      requiresAdmin: false,
      security: {
        dataAccessed: ['Task titles, assignees, due dates, estimates'],
        authentication: 'Internal Agent Worker',
        dataStorage: 'Workspace database',
        externalServices: ['Local AI Model'],
        dataBoundaries: 'Strictly workspace scoped',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'data-insights',
    name: 'Data Insights & SQL Assistant',
    tagline: 'Natural language queries to SQL statements, metric chart generation, and KPI anomaly alerts',
    description: `Democratize data analysis across your organization. Ask questions in plain English to generate SQL queries, visualize metric trends with interactive charts, and receive intelligent anomaly alerts when key business KPIs fluctuate unexpectedly.`,
    category: 'Analytics',
    version: '1.8.0',
    iconUrl: 'icon:search',
    tags: ['sql', 'analytics', 'kpi', 'metrics', 'charts', 'data', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Plain English to SQL query generation with schema awareness',
        'Automatic chart and graph rendering inside chat responses',
        'Anomaly detection across weekly recurring metric time-series',
      ],
      permissions: [
        { scope: 'read:analytics', name: 'Read analytics data', level: 'READ', description: 'Query telemetry tables' },
        { scope: 'write:messages', name: 'Post metric cards', level: 'WRITE', description: 'Render interactive chart components' },
        { scope: 'ai:invoke', name: 'SQL & Chart AI', level: 'READ', description: 'Formulate query structures' },
      ],
      commands: [
        { command: '/agent query', description: 'Ask data question and receive chart + SQL', args: '<question>' },
      ],
      examplePrompts: [
        'Show weekly active user growth for the past 6 months',
        'Compare message volume between #product and #engineering',
        'What was the median task completion time last month?',
      ],
      requiresAdmin: true,
      security: {
        dataAccessed: ['Aggregated analytics tables, schema definitions'],
        authentication: 'Read-only Database Role',
        dataStorage: 'No persistent query storage',
        externalServices: ['Local AI Model'],
        dataBoundaries: 'Strictly read-only schema queries. No mutation permitted.',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
  {
    kind: 'AGENT',
    slug: 'devops-commander',
    name: 'DevOps & Incident Commander',
    tagline: 'Orchestrates incident triage, status page updates, alert deduplication, and post-mortem creation',
    description: `Accelerate incident response and restore service reliability faster. When an incident is declared, DevOps Commander provisions dedicated war-room channels, polls server error logs, deduplicates alerting noise, drafts stakeholder updates, and compiles incident timelines for blameless post-mortems.`,
    category: 'Engineering',
    version: '1.6.0',
    iconUrl: 'icon:shield',
    tags: ['devops', 'incident', 'sre', 'status-page', 'reliability', 'oncall', 'ai-agent'],
    pricingModel: 'FREE',
    priceCents: 0,
    publisherSlug: 'onetab-official',
    publisherName: 'OneTab AI Labs',
    manifest: {
      entityType: 'AGENT',
      badge: 'OFFICIAL',
      capabilities: [
        'Incident declaration with automatic war room channel creation',
        'Real-time alert aggregation and error log summarization',
        'Drafting customer status page updates and stakeholder memos',
        'Post-incident review timeline compilation',
      ],
      permissions: [
        { scope: 'write:channels', name: 'Create incident channels', level: 'WRITE', description: 'Spin up war rooms' },
        { scope: 'write:messages', name: 'Post incident alerts', level: 'WRITE', description: 'Broadcast severity alerts' },
        { scope: 'write:documents', name: 'Generate post-mortems', level: 'WRITE', description: 'Draft post-incident documentation' },
        { scope: 'write:workspace', name: 'Incident coordinator role', level: 'ADMIN', description: 'Manage on-call notifications' },
      ],
      commands: [
        { command: '/agent declare-incident', description: 'Declare a new incident', args: '<sev1 | sev2 | sev3> <summary>' },
        { command: '/agent postmortem', description: 'Compile post-mortem timeline from current channel' },
      ],
      examplePrompts: [
        'Declare SEV-1 incident: Payment gateway response timeout',
        'Gather server error logs from the last 30 minutes',
        'Draft a customer-facing status page update for current degraded performance',
      ],
      requiresAdmin: true,
      security: {
        dataAccessed: ['System error logs, incident communication transcripts'],
        authentication: 'Privileged System Agent',
        dataStorage: 'Archived incident records',
        externalServices: ['Monitoring Endpoints'],
        dataBoundaries: 'Workspace boundary enforced',
      },
      compatibility: { platforms: ['Web', 'Desktop', 'Mobile'] },
    },
  },
];
