export const DEFAULT_THEMES = {
  light: 'github-light',
  dark: 'github-dark',
} as const;

export const LANGUAGE_ALIASES: Record<string, string> = {
  js: 'javascript',
  jsx: 'jsx',
  ts: 'typescript',
  tsx: 'tsx',
  mjs: 'javascript',
  cjs: 'javascript',
  mts: 'typescript',
  cts: 'typescript',
  py: 'python',
  python3: 'python',
  sh: 'bash',
  shell: 'bash',
  zsh: 'bash',
  bash: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  md: 'markdown',
  markdown: 'markdown',
  mdown: 'markdown',
  html: 'html',
  htm: 'html',
  xml: 'xml',
  svg: 'xml',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  json: 'json',
  jsonc: 'jsonc',
  c: 'c',
  cpp: 'cpp',
  'c++': 'cpp',
  cs: 'csharp',
  csharp: 'csharp',
  go: 'go',
  golang: 'go',
  rs: 'rust',
  rust: 'rust',
  rb: 'ruby',
  ruby: 'ruby',
  php: 'php',
  java: 'java',
  kt: 'kotlin',
  kotlin: 'kotlin',
  swift: 'swift',
  sql: 'sql',
  pgsql: 'sql',
  mysql: 'sql',
  diff: 'diff',
  patch: 'diff',
  docker: 'dockerfile',
  dockerfile: 'dockerfile',
  graphql: 'graphql',
  gql: 'graphql',
  proto: 'proto',
  text: 'plaintext',
  txt: 'plaintext',
  plain: 'plaintext',
};

export const LANGUAGE_NAMES: Record<string, string> = {
  javascript: 'JavaScript',
  jsx: 'JSX',
  typescript: 'TypeScript',
  tsx: 'TSX',
  python: 'Python',
  bash: 'Bash',
  yaml: 'YAML',
  markdown: 'Markdown',
  html: 'HTML',
  xml: 'XML',
  css: 'CSS',
  scss: 'SCSS',
  sass: 'Sass',
  less: 'Less',
  json: 'JSON',
  jsonc: 'JSON with Comments',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  go: 'Go',
  rust: 'Rust',
  ruby: 'Ruby',
  php: 'PHP',
  java: 'Java',
  kotlin: 'Kotlin',
  swift: 'Swift',
  sql: 'SQL',
  diff: 'Diff',
  dockerfile: 'Dockerfile',
  graphql: 'GraphQL',
  proto: 'Protobuf',
  plaintext: 'Plain Text',
};

export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  javascript: 'js',
  jsx: 'jsx',
  typescript: 'ts',
  tsx: 'tsx',
  python: 'py',
  bash: 'sh',
  yaml: 'yaml',
  markdown: 'md',
  html: 'html',
  xml: 'xml',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  json: 'json',
  jsonc: 'json',
  c: 'c',
  cpp: 'cpp',
  csharp: 'cs',
  go: 'go',
  rust: 'rs',
  ruby: 'rb',
  php: 'php',
  java: 'java',
  kotlin: 'kt',
  swift: 'swift',
  sql: 'sql',
  diff: 'diff',
  dockerfile: 'dockerfile',
  graphql: 'gql',
  plaintext: 'txt',
};

export const LANGUAGE_MIME_TYPES: Record<string, string> = {
  javascript: 'text/javascript',
  jsx: 'text/javascript',
  typescript: 'text/typescript',
  tsx: 'text/typescript',
  python: 'text/x-python',
  bash: 'application/x-sh',
  yaml: 'text/yaml',
  markdown: 'text/markdown',
  html: 'text/html',
  xml: 'application/xml',
  css: 'text/css',
  scss: 'text/x-scss',
  sass: 'text/x-sass',
  less: 'text/x-less',
  json: 'application/json',
  jsonc: 'application/json',
  c: 'text/x-c',
  cpp: 'text/x-c++',
  csharp: 'text/x-csharp',
  go: 'text/x-go',
  rust: 'text/x-rust',
  ruby: 'text/x-ruby',
  php: 'application/x-httpd-php',
  java: 'text/x-java',
  kotlin: 'text/x-kotlin',
  swift: 'text/x-swift',
  sql: 'application/sql',
  diff: 'text/x-diff',
  dockerfile: 'text/x-dockerfile',
  graphql: 'application/graphql',
  plaintext: 'text/plain',
};

export const CORE_SHIKI_LANGUAGES = [
  'javascript',
  'jsx',
  'typescript',
  'tsx',
  'json',
  'jsonc',
  'bash',
  'python',
  'html',
  'css',
  'markdown',
  'sql',
  'yaml',
  'diff',
] as const;

export const TERMINAL_LANGUAGES = new Set(['bash', 'sh', 'shell', 'zsh', 'terminal', 'console']);
